// AUTO-GENERATED by scripts/build-day-summaries.mjs. Do not edit by hand.
// Regenerate after changing day markdown files: node scripts/build-day-summaries.mjs
// Source: docs/product-mastery-track

export type DaySummary = {
  dayNumber: number;
  week: number;
  dayInWeek: number;
  title: string;
  duration: number;
  hasReflection: boolean;
};

export const DAY_SUMMARIES: DaySummary[] = [
  {
    "dayNumber": 1,
    "week": 1,
    "dayInWeek": 1,
    "title": "Pro Achiever 3.0 — APA Foundations — What It Is + The Signature Pitch Concept",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 2,
    "week": 1,
    "dayInWeek": 2,
    "title": "Pro Achiever 3.0 — Run the Meeting — Fact-Find + 7-Phase Pitch Flow",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 3,
    "week": 1,
    "dayInWeek": 3,
    "title": "Pro Achiever 3.0 — The Math + The Q&A — Numbers, Charges, Top 5 Client Questions",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 4,
    "week": 1,
    "dayInWeek": 4,
    "title": "Pro Achiever 3.0 — Defence + Expansion — Top 5 Objections + Cross-sell",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 5,
    "week": 1,
    "dayInWeek": 5,
    "title": "Pro Achiever 3.0 — Compliance + Close — Disclosures, Paperwork, Post-Close Referral Architecture",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 6,
    "week": 2,
    "dayInWeek": 1,
    "title": "Pro Lifetime Protector — PLP Foundations — Two-in-One Plan + Lifeboat-on-the-Ship",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 7,
    "week": 2,
    "dayInWeek": 2,
    "title": "Pro Lifetime Protector — Run the Meeting — Fact-Find + 5-Step Pitch Flow",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 8,
    "week": 2,
    "dayInWeek": 3,
    "title": "Pro Lifetime Protector — The Math + The Q&A — Premium Charges, LCC, Top 5 Questions",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 9,
    "week": 2,
    "dayInWeek": 4,
    "title": "Pro Lifetime Protector — Defence + Expansion — PLP-vs-GPP/APA/Term + Cross-sell",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 10,
    "week": 2,
    "dayInWeek": 5,
    "title": "Pro Lifetime Protector — Compliance + Close — ILP Disclosures, Budget-Choice Close, Retention",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 11,
    "week": 3,
    "dayInWeek": 1,
    "title": "Guaranteed Protect Plus — GPP Foundations — What It Is + The Rocket-Ship Diagram",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 12,
    "week": 3,
    "dayInWeek": 2,
    "title": "Guaranteed Protect Plus — Run the Meeting — Fact-Find + 6-Phase Pitch Flow",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 13,
    "week": 3,
    "dayInWeek": 3,
    "title": "Guaranteed Protect Plus — The Math + The Q&A — Numbers, Charges, Top 5 Client Questions",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 14,
    "week": 3,
    "dayInWeek": 4,
    "title": "Guaranteed Protect Plus — Defence + Expansion — Top 5 Objections + Cross-sell",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 15,
    "week": 3,
    "dayInWeek": 5,
    "title": "Guaranteed Protect Plus — Compliance + Close — Disclosures, Four-Hoops Close, Paperwork, Delivery",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 16,
    "week": 4,
    "dayInWeek": 1,
    "title": "Ultimate Critical Cover — UCC Foundations — Pure-CI Distinction + Multi-Claim Staircase",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 17,
    "week": 4,
    "dayInWeek": 2,
    "title": "Ultimate Critical Cover — Run the Meeting — 5 Power Questions + 5-Phase Pitch Flow",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 18,
    "week": 4,
    "dayInWeek": 3,
    "title": "Ultimate Critical Cover — The Math + The Q&A — Caps, Enhancer Mechanics, Top 5 Questions",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 19,
    "week": 4,
    "dayInWeek": 4,
    "title": "Ultimate Critical Cover — Defence + Expansion — 5 Objections + GPP+UCC Canonical Pair",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 20,
    "week": 4,
    "dayInWeek": 5,
    "title": "Ultimate Critical Cover — Compliance + Close — 6 Compliance Pillars + Term-Then-Rider Close",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 21,
    "week": 5,
    "dayInWeek": 1,
    "title": "HealthShield Gold Max — HSGM Foundations — What It Is + First-Line-of-Defence + Travel Package",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 22,
    "week": 5,
    "dayInWeek": 2,
    "title": "HealthShield Gold Max — Run the Meeting — Fact-Find + 8-Phase Pitch Flow",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 23,
    "week": 5,
    "dayInWeek": 3,
    "title": "HealthShield Gold Max — The Math + The Q&A — Numbers, Charges, Top 5 Client Questions",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 24,
    "week": 5,
    "dayInWeek": 4,
    "title": "HealthShield Gold Max — Defence + Expansion — Top 5 Objections + Cross-sell",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 25,
    "week": 5,
    "dayInWeek": 5,
    "title": "HealthShield Gold Max — Compliance + Close — Disclosures, Two-Option Close, Paperwork, Delivery",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 26,
    "week": 6,
    "dayInWeek": 1,
    "title": "Solitaire PA — Solitaire PA Foundations — Universal-Fit + Partial-Disability Gap",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 27,
    "week": 6,
    "dayInWeek": 2,
    "title": "Solitaire PA — Run the Meeting — Fact-Find + 7-Phase Pitch Flow",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 28,
    "week": 6,
    "dayInWeek": 3,
    "title": "Solitaire PA — The Math + The Q&A — 4 Plans × 8 Benefits + Top 5 Questions",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 29,
    "week": 6,
    "dayInWeek": 4,
    "title": "Solitaire PA — Defence + Expansion — Top 5 Objections + Total Wealth Bucket 4",
    "duration": 55,
    "hasReflection": false
  },
  {
    "dayNumber": 30,
    "week": 6,
    "dayInWeek": 5,
    "title": "Solitaire PA — Compliance + Close — Disclosures, Direct Close, Self-Claim Handoff",
    "duration": 50,
    "hasReflection": false
  },
  {
    "dayNumber": 31,
    "week": 7,
    "dayInWeek": 1,
    "title": "Platinum Wealth Venture — PWV Foundations — 5-Min Intro + THE Drawing Concept",
    "duration": 70,
    "hasReflection": false
  },
  {
    "dayNumber": 32,
    "week": 7,
    "dayInWeek": 2,
    "title": "Platinum Wealth Venture — Run the Meeting — 16-Point Discovery + 7-Phase Pitch Flow",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 33,
    "week": 7,
    "dayInWeek": 3,
    "title": "Platinum Wealth Venture — The Math + The Q&A — Healthcare Cost Angle, Color-Coded Review, Top 5 Questions",
    "duration": 60,
    "hasReflection": false
  },
  {
    "dayNumber": 34,
    "week": 7,
    "dayInWeek": 4,
    "title": "Platinum Wealth Venture — Defence + Expansion — Top 5 Objections + APA→PWV Restructure",
    "duration": 65,
    "hasReflection": false
  },
  {
    "dayNumber": 35,
    "week": 7,
    "dayInWeek": 5,
    "title": "Platinum Wealth Venture — Compliance + Close — ILP Disclosures + Gentle Close + 12-Item Execution Checklist",
    "duration": 65,
    "hasReflection": false
  }
];

export const TOTAL_DAYS = DAY_SUMMARIES.length;

export const DAYS_WITH_REFLECTION: ReadonlySet<number> = new Set(
  DAY_SUMMARIES.filter((d) => d.hasReflection).map((d) => d.dayNumber),
);
