// AUTO-GENERATED by scripts/build-day-summaries.mjs. Do not edit by hand.
// Regenerate after changing day markdown files: node scripts/build-day-summaries.mjs
// Source: docs/next-60-days

export type DaySummary = {
  dayNumber: number;
  week: number;
  dayInWeek: number;
  title: string;
  duration: number;
  hasReflection: boolean;
};

export const DAY_SUMMARIES: DaySummary[] = [
  {
    "dayNumber": 1,
    "week": 1,
    "dayInWeek": 1,
    "title": "Day 1 of Your Real Career — What Changes Now You're Licensed",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 2,
    "week": 1,
    "dayInWeek": 2,
    "title": "The Activity Math — Appointments × Close Rate × Case Size",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 3,
    "week": 1,
    "dayInWeek": 3,
    "title": "Your 90-Day Scorecard — KPIs + Revenue Math",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 4,
    "week": 1,
    "dayInWeek": 4,
    "title": "Your Story — First Real Draft",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 5,
    "week": 1,
    "dayInWeek": 5,
    "title": "Tonality & Salesmanship — How You Say It",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 6,
    "week": 1,
    "dayInWeek": 6,
    "title": "Practice — Record Your 90-Second Intro",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 7,
    "week": 2,
    "dayInWeek": 1,
    "title": "The Intent Statement — Framework",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 8,
    "week": 2,
    "dayInWeek": 2,
    "title": "The Intent Statement — Your Pattern Interrupt",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 9,
    "week": 2,
    "dayInWeek": 3,
    "title": "Positioning — The Objective Advisor",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 10,
    "week": 2,
    "dayInWeek": 4,
    "title": "Personal Branding P1 — Profile as Compound Asset",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 11,
    "week": 2,
    "dayInWeek": 5,
    "title": "Personal Branding P2 — Content + Stories Rhythm",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 12,
    "week": 2,
    "dayInWeek": 6,
    "title": "Practice — Deliver Your Intent Statement to 3 Prospects",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 13,
    "week": 3,
    "dayInWeek": 1,
    "title": "The 5 Silent Questions — What Prospects Check Before DMing You",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 14,
    "week": 3,
    "dayInWeek": 2,
    "title": "Testimonials That Actually Convert",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 15,
    "week": 3,
    "dayInWeek": 3,
    "title": "Digital Pipeline Hygiene — Where Leads Actually Live",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 16,
    "week": 3,
    "dayInWeek": 4,
    "title": "The DM Funnel — Reply Scripts",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 17,
    "week": 3,
    "dayInWeek": 5,
    "title": "CRAB Framework — Handling Blue Ticks",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 18,
    "week": 3,
    "dayInWeek": 6,
    "title": "Practice — 3 Posts Shipped, 5 DM Conversations Opened",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 19,
    "week": 4,
    "dayInWeek": 1,
    "title": "Prospecting Mindset — The Master Map",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 20,
    "week": 4,
    "dayInWeek": 2,
    "title": "Reaching Out Without Feeling Salesy",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 21,
    "week": 4,
    "dayInWeek": 3,
    "title": "Market Survey — The Warm-Market Framework",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 22,
    "week": 4,
    "dayInWeek": 4,
    "title": "Cold Prospecting + the ABCD Promises",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 23,
    "week": 4,
    "dayInWeek": 5,
    "title": "Your Pipeline Board — Tools and Weekly Review",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 24,
    "week": 4,
    "dayInWeek": 6,
    "title": "Practice — 30 Outreaches, 5 Appointments Booked",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 25,
    "week": 5,
    "dayInWeek": 1,
    "title": "Why Newly-Joined FCs Under-Ask — and Why It Compounds",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 26,
    "week": 5,
    "dayInWeek": 2,
    "title": "The Referral Asking Framework",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 27,
    "week": 5,
    "dayInWeek": 3,
    "title": "Quality of the Ask — Context > Script",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 28,
    "week": 5,
    "dayInWeek": 4,
    "title": "The Scripts Day — FACT Method + 10-Name Ask + Coaching the Client",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 29,
    "week": 5,
    "dayInWeek": 5,
    "title": "The Flywheel + the CAR Diagnostic",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 30,
    "week": 5,
    "dayInWeek": 6,
    "title": "Practice — 10 Referral Asks Delivered, 3 Referrals Logged",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 31,
    "week": 6,
    "dayInWeek": 1,
    "title": "DISC — Four Profiles + the 5-Minute Speed-Read",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 32,
    "week": 6,
    "dayInWeek": 2,
    "title": "D Profile — Direct, Dominant, Decisive",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 33,
    "week": 6,
    "dayInWeek": 3,
    "title": "I Profile — Influencing, Social, Expressive",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 34,
    "week": 6,
    "dayInWeek": 4,
    "title": "S Profile — Steady, Supportive, Patient",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 35,
    "week": 6,
    "dayInWeek": 5,
    "title": "C Profile — Conscientious, Analytical, Cautious",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 36,
    "week": 6,
    "dayInWeek": 6,
    "title": "Practice — Roleplay All 4 Profiles on Camera",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 37,
    "week": 7,
    "dayInWeek": 1,
    "title": "Hot Buttons I — What Actually Drives Buying",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 38,
    "week": 7,
    "dayInWeek": 2,
    "title": "Hot Buttons II — Mapping Value to Emotion",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 39,
    "week": 7,
    "dayInWeek": 3,
    "title": "Hot Buttons III — Pain-Before-Gain Framing",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 40,
    "week": 7,
    "dayInWeek": 4,
    "title": "Objection Turnaround — Anchor-Disrupt-Ask + ART + Iceberg",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 41,
    "week": 7,
    "dayInWeek": 5,
    "title": "Pitch Mechanics — Confidence Language + the 4 Closes",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 42,
    "week": 7,
    "dayInWeek": 6,
    "title": "Practice — 3 Pitches, 3 Profiles, 3 Hot Buttons",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 43,
    "week": 8,
    "dayInWeek": 1,
    "title": "Asking the Right Questions I — The Power Question",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 44,
    "week": 8,
    "dayInWeek": 2,
    "title": "Asking the Right Questions II — Silence as a Tool",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 45,
    "week": 8,
    "dayInWeek": 3,
    "title": "Sales Angles — Wealth, Risk, Legacy, Lifestyle",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 46,
    "week": 8,
    "dayInWeek": 4,
    "title": "Choosing the Right Angle for This Prospect",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 47,
    "week": 8,
    "dayInWeek": 5,
    "title": "Analyzing Products + Crafting the Pitch",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 48,
    "week": 8,
    "dayInWeek": 6,
    "title": "Practice — 1 Live Pitch on Camera, Self-Reviewed",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 49,
    "week": 9,
    "dayInWeek": 1,
    "title": "Closing I — The Trial Close + Paper-Flip Social Proof",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 50,
    "week": 9,
    "dayInWeek": 2,
    "title": "Closing II — Assumptive, Choice, Urgency",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 51,
    "week": 9,
    "dayInWeek": 3,
    "title": "Closing III — Emotional Close vs Logical Close",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 52,
    "week": 9,
    "dayInWeek": 4,
    "title": "The 3 Magic Questions on Objections",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 53,
    "week": 9,
    "dayInWeek": 5,
    "title": "Top 10 Objections + Scripts",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 54,
    "week": 9,
    "dayInWeek": 6,
    "title": "Practice — 5 Objection Drills Recorded",
    "duration": 45,
    "hasReflection": false
  },
  {
    "dayNumber": 55,
    "week": 10,
    "dayInWeek": 1,
    "title": "Policy Restructuring — When and Ethics",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 56,
    "week": 10,
    "dayInWeek": 2,
    "title": "After Sales — Onboarding Your First Client",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 57,
    "week": 10,
    "dayInWeek": 3,
    "title": "Building Moments — The Touch-Point Calendar",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 58,
    "week": 10,
    "dayInWeek": 4,
    "title": "Case Study — How a Top Producer Actually Runs a Week",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 59,
    "week": 10,
    "dayInWeek": 5,
    "title": "Your First $X FYC — Reviewing Your Numbers",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 60,
    "week": 10,
    "dayInWeek": 6,
    "title": "Graduation — The 12-Month Plan",
    "duration": 45,
    "hasReflection": false
  }
];

export const TOTAL_DAYS = DAY_SUMMARIES.length;

export const DAYS_WITH_REFLECTION: ReadonlySet<number> = new Set(
  DAY_SUMMARIES.filter((d) => d.hasReflection).map((d) => d.dayNumber),
);
