import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { PageLayout } from "@/components/layout/PageLayout";
import { BrandedPageHeader } from "@/components/layout/BrandedPageHeader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Search,
  Image as ImageIcon,
  Check,
  X,
  ChevronLeft,
  Pencil,
  Loader2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import {
  useConceptCards,
  useConceptCardsMutations,
  type ConceptCard,
} from "@/hooks/useConceptCards";
import photoDescriptionsRaw from "@/data/photo-descriptions.json";
import { DescribeAndBindDialog } from "@/components/admin/DescribeAndBindDialog";

// Per-URL description bundled into the page chunk so search can match the
// AI-generated topic tags + one-line summary, and the photo grid can show
// a caption on hover. Generated by tools/describe-clusters.py — re-run
// that to refresh after adding more photos.
interface PhotoDescription {
  url: string;
  cluster_id: number;
  cluster_size: number;
  is_representative: boolean;
  kind: string;
  topics: string[];
  key_numbers: string[];
  client_or_generic: string;
  one_line_summary: string;
}
const PHOTO_DESCRIPTIONS: Map<string, PhotoDescription> = new Map(
  (photoDescriptionsRaw as PhotoDescription[]).map((d) => [d.url, d])
);

interface EnhancedPhoto {
  /** Storage file name, e.g. enhanced_1778880032994_photo_2025-...png */
  name: string;
  /** Public URL */
  url: string;
  /** ISO timestamp from the storage object */
  createdAt: string;
}

const STORAGE_BUCKET = "concept-card-images";
const STORAGE_FOLDER = "enhanced";

async function listEnhancedPhotos(): Promise<EnhancedPhoto[]> {
  // Supabase storage `list()` is paginated; iterate until we've consumed all.
  const page = 100;
  let offset = 0;
  const all: EnhancedPhoto[] = [];
  while (true) {
    const { data, error } = await supabase.storage
      .from(STORAGE_BUCKET)
      .list(STORAGE_FOLDER, {
        limit: page,
        offset,
        sortBy: { column: "created_at", order: "desc" },
      });
    if (error) throw error;
    if (!data || data.length === 0) break;
    for (const f of data) {
      const path = `${STORAGE_FOLDER}/${f.name}`;
      const { data: pub } = supabase.storage
        .from(STORAGE_BUCKET)
        .getPublicUrl(path);
      all.push({
        name: f.name,
        url: pub.publicUrl,
        createdAt: f.created_at ?? "",
      });
    }
    if (data.length < page) break;
    offset += page;
  }
  return all;
}

// ─── Card list item (left pane) ─────────────────────────────────────────
function CardRow({
  card,
  selected,
  onSelect,
}: {
  card: ConceptCard;
  selected: boolean;
  onSelect: () => void;
}) {
  const imgs = (card.image_urls && card.image_urls.length > 0
    ? card.image_urls
    : card.image_url
      ? [card.image_url]
      : []) as string[];
  return (
    <button
      onClick={onSelect}
      className={cn(
        "w-full text-left rounded-xl border p-2.5 transition-all",
        selected
          ? "border-primary bg-primary/5 ring-2 ring-primary/30"
          : "border-border hover:border-primary/40 hover:bg-muted/30"
      )}
    >
      <div className="flex items-start gap-3">
        <div className="shrink-0 w-20 h-20 rounded-md bg-white border border-border/40 flex items-center justify-center overflow-hidden">
          {imgs.length > 0 ? (
            <img
              src={imgs[0]}
              alt=""
              className="w-full h-full object-contain"
              loading="lazy"
            />
          ) : (
            <ImageIcon className="h-5 w-5 text-muted-foreground/50" />
          )}
        </div>
        <div className="flex-1 min-w-0">
          <div className="text-sm font-medium leading-snug line-clamp-2">
            {card.title}
          </div>
          <div className="flex flex-wrap gap-1 mt-1">
            {imgs.length > 0 ? (
              <Badge
                variant="outline"
                className="text-[9px] border-emerald-300 text-emerald-700 dark:text-emerald-400 px-1.5 py-0"
              >
                {imgs.length} image{imgs.length === 1 ? "" : "s"}
              </Badge>
            ) : (
              <Badge
                variant="outline"
                className="text-[9px] border-amber-300 text-amber-700 dark:text-amber-400 px-1.5 py-0"
              >
                no image
              </Badge>
            )}
            {card.tags?.slice(0, 2).map((t) => (
              <Badge
                key={t}
                variant="outline"
                className="text-[9px] px-1.5 py-0"
              >
                {t}
              </Badge>
            ))}
          </div>
        </div>
      </div>
    </button>
  );
}

// ─── Photo grid tile (right pane) ───────────────────────────────────────
function PhotoTile({
  photo,
  alreadyAssignedTo,
  selectedCardHasIt,
  busy,
  onAssign,
}: {
  photo: EnhancedPhoto;
  alreadyAssignedTo: string[];
  selectedCardHasIt: boolean;
  busy: boolean;
  onAssign: () => void;
}) {
  const desc = PHOTO_DESCRIPTIONS.get(photo.url);
  // Compose a tooltip that shows the AI-generated summary + key topics.
  // Browsers truncate `title` at varying lengths so we keep it compact.
  const tooltipText = desc
    ? [
        desc.one_line_summary,
        desc.topics.length ? `Topics: ${desc.topics.join(", ")}` : "",
        desc.key_numbers.length ? `Numbers: ${desc.key_numbers.join(", ")}` : "",
        `(${desc.kind.replace(/_/g, " ")}; ${desc.client_or_generic.replace("_", "-")})`,
      ].filter(Boolean).join("\n")
    : photo.name;
  return (
    <button
      onClick={onAssign}
      disabled={busy}
      title={tooltipText}
      className={cn(
        "group relative rounded-lg overflow-hidden border bg-card transition-all text-left",
        selectedCardHasIt
          ? "border-emerald-400 ring-2 ring-emerald-200 dark:ring-emerald-900/60"
          : alreadyAssignedTo.length > 0
            ? "border-amber-300 hover:border-amber-400"
            : "border-border hover:border-primary/60"
      )}
    >
      <div className="aspect-square bg-white">
        <img
          src={photo.url}
          alt={desc?.one_line_summary ?? photo.name}
          loading="lazy"
          className="w-full h-full object-contain"
        />
      </div>
      {selectedCardHasIt && (
        <div className="absolute top-1 right-1 z-10 h-6 w-6 rounded-full bg-emerald-500 text-white flex items-center justify-center shadow-md">
          <Check className="h-3.5 w-3.5" />
        </div>
      )}
      {!selectedCardHasIt && alreadyAssignedTo.length > 0 && (
        <div className="absolute top-1 left-1 z-10 text-[9px] bg-amber-500 text-white px-1.5 py-0.5 rounded font-medium shadow-md">
          assigned to {alreadyAssignedTo.length}
        </div>
      )}
      {/* Caption strip on hover — reveals the AI summary so you don't need
          to hover-and-wait for the OS tooltip to fire. */}
      {desc && (
        <div className="absolute inset-x-0 bottom-0 z-10 translate-y-full group-hover:translate-y-0 transition-transform bg-black/80 text-white text-[10px] leading-snug px-2 py-1.5 pointer-events-none">
          <div className="line-clamp-3">{desc.one_line_summary}</div>
          {desc.topics.length > 0 && (
            <div className="mt-0.5 opacity-80 line-clamp-1">
              {desc.topics.slice(0, 4).join(" · ")}
            </div>
          )}
        </div>
      )}
      {busy && (
        <div className="absolute inset-0 bg-background/80 flex items-center justify-center">
          <Loader2 className="h-5 w-5 animate-spin text-primary" />
        </div>
      )}
    </button>
  );
}

// ─── Page ───────────────────────────────────────────────────────────────
export default function AssignDrawingsPage() {
  const { cards, refetch } = useConceptCards();
  const { updateCard } = useConceptCardsMutations();
  const [photos, setPhotos] = useState<EnhancedPhoto[] | null>(null);
  const [photosLoading, setPhotosLoading] = useState(true);
  const [photosError, setPhotosError] = useState<string | null>(null);
  const [selectedCardId, setSelectedCardId] = useState<string | null>(null);
  const [cardFilter, setCardFilter] = useState<"all" | "missing">("missing");
  const [cardSearch, setCardSearch] = useState("");
  const [photoSearch, setPhotoSearch] = useState("");
  // Photo filter — default "unbound" so the grid shrinks as you bind, leaving
  // only photos that haven't been attached to any card yet.
  const [photoFilter, setPhotoFilter] = useState<"all" | "unbound">("unbound");
  const [busyPhotoUrl, setBusyPhotoUrl] = useState<string | null>(null);
  // Describe-and-bind dialog state. Clicking a photo when no card is selected
  // opens this; lets you either bind to an existing card OR create a new one.
  const [describePhoto, setDescribePhoto] = useState<EnhancedPhoto | null>(null);

  useEffect(() => {
    let cancelled = false;
    setPhotosLoading(true);
    setPhotosError(null);
    listEnhancedPhotos()
      .then((p) => {
        if (!cancelled) setPhotos(p);
      })
      .catch((e) => {
        if (!cancelled) setPhotosError(String(e?.message ?? e));
      })
      .finally(() => {
        if (!cancelled) setPhotosLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // Reverse index: photo URL → list of card IDs that already include it.
  const photoToCardIds = useMemo(() => {
    const map = new Map<string, string[]>();
    for (const c of cards) {
      const urls = [
        ...(c.image_urls ?? []),
        ...(c.image_url ? [c.image_url] : []),
      ];
      for (const u of urls) {
        if (!u) continue;
        if (!map.has(u)) map.set(u, []);
        map.get(u)!.push(c.id);
      }
    }
    return map;
  }, [cards]);

  const filteredCards = useMemo(() => {
    const q = cardSearch.trim().toLowerCase();
    return cards
      .filter((c) => {
        if (cardFilter === "missing") {
          const has =
            (c.image_urls && c.image_urls.length > 0) || c.image_url;
          if (has) return false;
        }
        if (!q) return true;
        return (
          c.title.toLowerCase().includes(q) ||
          c.tags?.some((t) => t.toLowerCase().includes(q))
        );
      })
      .sort((a, b) => a.sort_order - b.sort_order);
  }, [cards, cardFilter, cardSearch]);

  // Photos not yet attached to any concept card.
  const unboundPhotos = useMemo(() => {
    if (!photos) return [];
    return photos.filter((p) => !photoToCardIds.has(p.url));
  }, [photos, photoToCardIds]);

  const filteredPhotos = useMemo(() => {
    if (!photos) return [];
    const base = photoFilter === "unbound" ? unboundPhotos : photos;
    const q = photoSearch.trim().toLowerCase();
    if (!q) return base;
    return base.filter((p) => {
      // Match on filename OR the AI-generated description (summary, topics,
      // key_numbers). Useful when looking for "retirement gap" / "1/3 rule"
      // / "$2.4M" etc — the filename is just a timestamp, so without the
      // description match the search would only ever find date prefixes.
      if (p.name.toLowerCase().includes(q)) return true;
      const desc = PHOTO_DESCRIPTIONS.get(p.url);
      if (!desc) return false;
      if (desc.one_line_summary.toLowerCase().includes(q)) return true;
      if (desc.topics.some((t) => t.toLowerCase().includes(q))) return true;
      if (desc.key_numbers.some((k) => k.toLowerCase().includes(q))) return true;
      if (desc.kind.includes(q)) return true;
      return false;
    });
  }, [photos, unboundPhotos, photoFilter, photoSearch]);

  const selectedCard = cards.find((c) => c.id === selectedCardId) ?? null;

  const handleAssign = async (photo: EnhancedPhoto) => {
    if (!selectedCard) {
      // No card selected → open the describe-and-bind dialog so you can
      // either pick an existing card or create a new one in one shot.
      setDescribePhoto(photo);
      return;
    }
    setBusyPhotoUrl(photo.url);
    const existing = selectedCard.image_urls ?? [];
    const already = existing.includes(photo.url);
    const newUrls = already
      ? existing.filter((u) => u !== photo.url)
      : [...existing, photo.url];

    // Also keep `image_url` (legacy single field) pointing at the first image
    // so older renderers / SRS hooks still find one.
    const ok = await updateCard(selectedCard.id, {
      image_urls: newUrls,
      image_url: newUrls[0] ?? null,
    });
    if (ok) {
      toast.success(already ? "Removed from card" : "Assigned to card");
      refetch();
    }
    setBusyPhotoUrl(null);
  };

  const missingCount = cards.filter(
    (c) => !((c.image_urls && c.image_urls.length > 0) || c.image_url)
  ).length;

  return (
    <PageLayout
      title="Assign drawings — admin"
      description="Bind enhanced handwritten photos to concept cards"
    >
      <BrandedPageHeader
        tone="dark"
        showOnMobile
        title="Assign drawings"
        subtitle={`Pick a concept card on the left, then click a photo on the right to assign. ${missingCount} card${missingCount === 1 ? "" : "s"} still missing an image.`}
        breadcrumbs={[
          { label: "Home", href: "/" },
          { label: "Admin", href: "/admin" },
          { label: "Assign drawings" },
        ]}
        actions={
          <Button asChild variant="outline" size="sm">
            <Link to="/concept-cards" className="gap-1.5">
              <ChevronLeft className="h-4 w-4" />
              Back to Concept Cards
            </Link>
          </Button>
        }
      />

      <div className="mx-auto px-3 md:px-6 py-3 md:py-6 max-w-7xl">
        <div className="grid grid-cols-1 lg:grid-cols-[360px_1fr] gap-4">
          {/* ─── LEFT: Cards list ───────────────────────────────── */}
          <Card className="lg:sticky lg:top-3 lg:self-start lg:max-h-[calc(100vh-2rem)]">
            <CardContent className="p-3 flex flex-col gap-2">
              <Tabs
                value={cardFilter}
                onValueChange={(v) => setCardFilter(v as "all" | "missing")}
              >
                <TabsList className="grid w-full grid-cols-2 h-8">
                  <TabsTrigger value="missing" className="text-xs">
                    Missing ({missingCount})
                  </TabsTrigger>
                  <TabsTrigger value="all" className="text-xs">
                    All ({cards.length})
                  </TabsTrigger>
                </TabsList>
                <TabsContent value={cardFilter} className="mt-0" />
              </Tabs>
              <div className="relative">
                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                <Input
                  placeholder="Filter cards..."
                  value={cardSearch}
                  onChange={(e) => setCardSearch(e.target.value)}
                  className="h-8 pl-7 text-xs"
                />
              </div>
              <div className="flex flex-col gap-1.5 overflow-y-auto max-h-[60vh] lg:max-h-[calc(100vh-12rem)] pr-1">
                {filteredCards.length === 0 ? (
                  <div className="rounded-xl border border-dashed bg-muted/20 p-4 text-center text-xs text-muted-foreground">
                    No cards match the current filter
                  </div>
                ) : (
                  filteredCards.map((c) => (
                    <CardRow
                      key={c.id}
                      card={c}
                      selected={selectedCardId === c.id}
                      onSelect={() => setSelectedCardId(c.id)}
                    />
                  ))
                )}
              </div>
            </CardContent>
          </Card>

          {/* ─── RIGHT: Photos grid ──────────────────────────────── */}
          <Card>
            <CardContent className="p-3 flex flex-col gap-3">
              {/* Selected-card summary */}
              {selectedCard ? (
                <div className="rounded-xl border border-primary/30 bg-primary/5 p-3">
                  <div className="flex items-start gap-2.5">
                    <Pencil className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                    <div className="flex-1 min-w-0">
                      <div className="text-[10px] font-semibold text-primary uppercase tracking-wide">
                        Assigning to
                      </div>
                      <div className="text-sm font-medium leading-snug">
                        {selectedCard.title}
                      </div>
                      {selectedCard.description ? (
                        <div className="text-[11px] text-muted-foreground mt-1 line-clamp-3">
                          {selectedCard.description}
                        </div>
                      ) : null}
                      <div className="text-[11px] text-muted-foreground mt-1">
                        {(() => {
                          const urls = [
                            ...(selectedCard.image_urls ?? []),
                            ...(selectedCard.image_url && !(selectedCard.image_urls ?? []).includes(selectedCard.image_url) ? [selectedCard.image_url] : []),
                          ];
                          return `${urls.length} image${urls.length === 1 ? "" : "s"} currently bound. Click a photo on the right to toggle.`;
                        })()}
                      </div>
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSelectedCardId(null)}
                      className="h-7 px-2 text-xs"
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                  {/* Currently-bound image strip — full-size enough to verify
                      the drawing matches the card concept. Click to unbind. */}
                  {(() => {
                    const boundUrls = [
                      ...(selectedCard.image_urls ?? []),
                      ...(selectedCard.image_url && !(selectedCard.image_urls ?? []).includes(selectedCard.image_url) ? [selectedCard.image_url] : []),
                    ];
                    if (boundUrls.length === 0) return null;
                    return (
                      <div className="mt-3 grid grid-cols-2 sm:grid-cols-3 gap-2">
                        {boundUrls.map((u) => {
                          const isBusy = busyPhotoUrl === u;
                          return (
                            <div
                              key={u}
                              className="group/img relative rounded-lg overflow-hidden border border-primary/40 bg-white aspect-[4/3]"
                            >
                              <a
                                href={u}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="block w-full h-full"
                                title="Open full-size in a new tab"
                              >
                                <img
                                  src={u}
                                  alt={selectedCard.title}
                                  loading="lazy"
                                  className="w-full h-full object-contain"
                                />
                                <div className="absolute inset-0 bg-black/0 group-hover/img:bg-black/30 transition-colors" />
                                <span className="absolute bottom-1 right-1 text-[9px] font-medium opacity-0 group-hover/img:opacity-100 transition-opacity bg-black/60 text-white px-1.5 py-0.5 rounded">
                                  Open ↗
                                </span>
                              </a>
                              {/* Unbind — one click removes this image from
                                  the card. Stops the parent anchor from
                                  opening the file at the same time. */}
                              <button
                                type="button"
                                disabled={isBusy}
                                onClick={(e) => {
                                  e.preventDefault();
                                  e.stopPropagation();
                                  // Synthesise an EnhancedPhoto so handleAssign
                                  // (which expects one) can toggle this URL
                                  // off the card.
                                  handleAssign({ name: "", url: u, createdAt: "" });
                                }}
                                className="absolute top-1 right-1 z-10 inline-flex items-center gap-1 rounded-md bg-destructive/90 hover:bg-destructive text-white text-[10px] font-medium px-1.5 py-0.5 shadow-sm disabled:opacity-50"
                                title="Unbind this drawing from the card"
                              >
                                {isBusy ? (
                                  <Loader2 className="h-3 w-3 animate-spin" />
                                ) : (
                                  <>
                                    <X className="h-3 w-3" />
                                    Unbind
                                  </>
                                )}
                              </button>
                            </div>
                          );
                        })}
                      </div>
                    );
                  })()}
                </div>
              ) : (
                <div className="rounded-xl border border-dashed border-sky-300 bg-sky-50/50 dark:bg-sky-950/20 p-3 text-xs text-sky-900 dark:text-sky-200">
                  No card selected — clicking a photo will open the{" "}
                  <strong>Describe &amp; Bind</strong> dialog, where you can
                  either pick an existing concept card or create a new one
                  from the drawing.
                </div>
              )}

              {/* Photo filter + search */}
              <div className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center">
                <Tabs
                  value={photoFilter}
                  onValueChange={(v) => setPhotoFilter(v as "all" | "unbound")}
                  className="sm:flex-none"
                >
                  <TabsList className="grid grid-cols-2 h-9 w-full sm:w-auto">
                    <TabsTrigger value="unbound" className="text-xs px-3">
                      Unbound ({unboundPhotos.length})
                    </TabsTrigger>
                    <TabsTrigger value="all" className="text-xs px-3">
                      All ({photos?.length ?? 0})
                    </TabsTrigger>
                  </TabsList>
                  <TabsContent value={photoFilter} className="mt-0" />
                </Tabs>
                <div className="relative flex-1">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                  <Input
                    placeholder={
                      photoFilter === "unbound"
                        ? `Search ${unboundPhotos.length} unbound photos by topic, number, or filename...`
                        : `Search ${photos?.length ?? "..."} photos by topic, number, or filename...`
                    }
                    value={photoSearch}
                    onChange={(e) => setPhotoSearch(e.target.value)}
                    className="h-9 pl-7 text-xs"
                  />
                </div>
              </div>

              {/* Photo grid */}
              {photosLoading ? (
                <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-2">
                  {Array.from({ length: 12 }).map((_, i) => (
                    <div
                      key={i}
                      className="aspect-square rounded-lg bg-muted/30 animate-pulse"
                    />
                  ))}
                </div>
              ) : photosError ? (
                <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">
                  Failed to load photos: {photosError}
                </div>
              ) : (photos?.length ?? 0) === 0 ? (
                <div className="rounded-xl border border-dashed bg-muted/20 p-6 text-center text-sm text-muted-foreground">
                  No enhanced photos found yet. Run{" "}
                  <code className="text-xs">tools/enhance-handwritten-drawings.py</code>{" "}
                  first.
                </div>
              ) : filteredPhotos.length === 0 ? (
                <div className="rounded-xl border border-dashed border-emerald-300 bg-emerald-50/40 dark:bg-emerald-950/20 p-6 text-center text-sm text-emerald-800 dark:text-emerald-300">
                  {photoFilter === "unbound"
                    ? `Every photo has been bound to at least one card. Switch to "All" to re-assign or remove bindings.`
                    : "No photos match the current search."}
                </div>
              ) : (
                <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-2">
                  {filteredPhotos.map((p) => {
                    const assignedTo = photoToCardIds.get(p.url) ?? [];
                    const selectedHasIt =
                      selectedCard != null &&
                      assignedTo.includes(selectedCard.id);
                    return (
                      <PhotoTile
                        key={p.url}
                        photo={p}
                        alreadyAssignedTo={assignedTo}
                        selectedCardHasIt={selectedHasIt}
                        busy={busyPhotoUrl === p.url}
                        onAssign={() => handleAssign(p)}
                      />
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>

      <DescribeAndBindDialog
        open={describePhoto != null}
        onOpenChange={(o) => {
          if (!o) setDescribePhoto(null);
        }}
        photoUrl={describePhoto?.url ?? null}
        photoName={describePhoto?.name ?? null}
        initialDescription={
          describePhoto
            ? PHOTO_DESCRIPTIONS.get(describePhoto.url)?.one_line_summary ?? ""
            : ""
        }
        cards={cards}
        onDone={() => {
          refetch();
        }}
      />
    </PageLayout>
  );
}
