import { useState, useMemo, useEffect } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { PageLayout } from "@/components/layout/PageLayout";
import { BrandedPageHeader } from "@/components/layout/BrandedPageHeader";
import { ScriptsHubHeaderTabs } from "@/components/scripts/ScriptsTabBar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Search, ExternalLink, ImageIcon, Pencil, X, RotateCcw } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  CASES,
  CASE_PRODUCTS,
  ALL_CASE_PLAYS,
  type CaseEntry,
  type CaseProduct,
} from "@/data/caseVault";
import caseReferencePhotosRaw from "@/data/case-reference-photos.json";

// Auto-suggested reference photos per case id. Generated by
// tools/match-photos-to-cases.py using product-mention + specific-dollar
// matches between the case's metadata and each photo's Telegram context +
// AI description. Strong-signal-only — generic tag-overlap matches are
// filtered out to keep false positives low.
interface CaseReferencePhoto {
  url: string;
  summary: string;
  score: number;
  evidence: string[];
}
const CASE_REFERENCE_PHOTOS = caseReferencePhotosRaw as Record<string, CaseReferencePhoto[]>;

const PRODUCT_FILTER_OPTIONS: ("All" | CaseProduct)[] = [
  "All",
  ...(Object.keys(CASE_PRODUCTS) as CaseProduct[]),
];

const PLAY_FILTER_OPTIONS = ["All", ...ALL_CASE_PLAYS];

// ─── Case Card ──────────────────────────────────────────────────────────
function CaseCard({
  entry,
  onOpen,
}: {
  entry: CaseEntry;
  onOpen: (entry: CaseEntry) => void;
}) {
  return (
    <button
      onClick={() => onOpen(entry)}
      className="group text-left rounded-2xl border bg-card shadow-sm overflow-hidden transition-all hover:shadow-md hover:border-primary/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary"
    >
      {/* Header strip */}
      <div className="flex items-center justify-between gap-2 px-4 py-2.5 border-b bg-muted/30">
        <div className="flex items-center gap-2 min-w-0">
          <Badge className="bg-primary/10 text-primary border-primary/20 text-[10px] px-1.5 py-0 font-mono shrink-0">
            Case {entry.code}
          </Badge>
          <span className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide truncate">
            {CASE_PRODUCTS[entry.product].label}
          </span>
        </div>
        <Pencil className="h-3.5 w-3.5 text-muted-foreground/40 group-hover:text-primary transition-colors shrink-0" />
      </div>

      {/* Body */}
      <div className="p-4 flex flex-col gap-2.5">
        <h3 className="font-semibold text-sm leading-snug line-clamp-2">
          {entry.title}
        </h3>

        <div className="text-xs text-muted-foreground space-y-1">
          <div>
            <span className="font-medium text-foreground/80">Prospect:</span>{" "}
            {entry.prospect}
          </div>
          <div>
            <span className="font-medium text-foreground/80">Anchor:</span>{" "}
            {entry.anchor}
          </div>
        </div>

        <div className="rounded-lg bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900/50 px-2.5 py-1.5">
          <div className="text-[9px] font-semibold text-emerald-700 dark:text-emerald-400 uppercase tracking-wide mb-0.5">
            Receipt
          </div>
          <div className="text-xs text-emerald-900 dark:text-emerald-200 leading-snug">
            {entry.headline}
          </div>
        </div>

        {/* Tags */}
        <div className="flex flex-wrap gap-1 pt-1">
          <Badge variant="outline" className="text-[10px] px-1.5 py-0">
            {entry.play.split("—")[0].trim()}
          </Badge>
          {entry.tags.slice(0, 2).map((t) => (
            <Badge key={t} variant="outline" className="text-[10px] px-1.5 py-0">
              {t}
            </Badge>
          ))}
        </div>

        {/* Drawings count */}
        {entry.drawings.length > 0 && (
          <div className="text-[10px] text-muted-foreground pt-0.5 flex items-center gap-1">
            <ImageIcon className="h-3 w-3" />
            {entry.drawings.length} drawing
            {entry.drawings.length > 1 ? "s" : ""} used
          </div>
        )}
      </div>
    </button>
  );
}

// ─── Detail Dialog ──────────────────────────────────────────────────────
// Strip the "Play X — " prefix from a play label so it reads naturally in
// a sentence (e.g. "whole-life / endowment restructure" instead of
// "Play A — Whole-life / endowment restructure").
function playInSentence(play: string): string {
  return play.replace(/^Play\s+[A-C]\s+[—–-]\s+/i, "").trim().toLowerCase();
}

// Strip the "(Play X receipt)" / "(receipt)" suffix and leading "The" so the
// title reads as a clean noun phrase for use mid-sentence.
function prospectFromTitle(title: string): string {
  return title
    .replace(/\s*\([^)]*receipt[^)]*\)\s*$/i, "")
    .replace(/^The\s+/i, "")
    .trim();
}

// ─── Reference photos grid (right-pane of CaseDetailDialog) ────────────
// Pulls the auto-matched reference photos for this case, lets the user
// "Not relevant" wrong matches (persisted to localStorage), and offers a
// reset button to unhide them. localStorage keys are namespaced per case
// so curating one case doesn't affect others.
function CaseReferencePhotos({ caseId }: { caseId: string }) {
  const HIDDEN_KEY = `case-vault.hidden-ref-photos.${caseId}`;
  const photos = CASE_REFERENCE_PHOTOS[caseId] ?? [];
  const [hiddenUrls, setHiddenUrls] = useState<Set<string>>(() => {
    if (typeof window === "undefined") return new Set();
    try {
      const raw = localStorage.getItem(HIDDEN_KEY);
      return new Set<string>(raw ? JSON.parse(raw) : []);
    } catch {
      return new Set();
    }
  });

  // Re-read localStorage when caseId changes (the same component instance
  // is reused as the dialog swaps cases).
  useEffect(() => {
    try {
      const raw = localStorage.getItem(HIDDEN_KEY);
      setHiddenUrls(new Set<string>(raw ? JSON.parse(raw) : []));
    } catch {
      setHiddenUrls(new Set());
    }
  }, [HIDDEN_KEY]);

  const persist = (next: Set<string>) => {
    setHiddenUrls(next);
    try {
      localStorage.setItem(HIDDEN_KEY, JSON.stringify(Array.from(next)));
    } catch {
      /* localStorage full / disabled — silently degrade */
    }
  };

  const visible = photos.filter((p) => !hiddenUrls.has(p.url));
  if (photos.length === 0) return null;

  const allHidden = visible.length === 0 && hiddenUrls.size > 0;

  return (
    <div>
      <div className="flex items-baseline justify-between mb-1.5 gap-2 flex-wrap">
        <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide">
          Reference photos from the case-study chat ({visible.length}
          {hiddenUrls.size > 0 ? <span className="text-amber-600 dark:text-amber-400"> · {hiddenUrls.size} hidden</span> : null})
        </div>
        <div className="flex items-center gap-2 text-[9px]">
          <span className="text-muted-foreground/60 italic">auto-matched · hover for description · ✕ to hide</span>
          {hiddenUrls.size > 0 && (
            <button
              type="button"
              onClick={() => persist(new Set())}
              className="inline-flex items-center gap-1 text-primary hover:underline"
              title="Unhide every photo you previously marked Not relevant for this case"
            >
              <RotateCcw className="h-3 w-3" />
              Reset
            </button>
          )}
        </div>
      </div>
      {allHidden ? (
        <div className="rounded-lg border border-dashed border-amber-300 bg-amber-50/50 dark:bg-amber-950/20 p-3 text-xs text-amber-900 dark:text-amber-200">
          All auto-matched photos for this case were marked Not relevant. Click Reset above to unhide them.
        </div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {visible.map((p) => (
            <div
              key={p.url}
              className="group/refimg relative rounded-lg overflow-hidden border bg-white aspect-[4/3] hover:border-primary/60 transition-colors"
            >
              <a
                href={p.url}
                target="_blank"
                rel="noopener noreferrer"
                title={`${p.summary}\n\nEvidence: ${p.evidence.join(", ")}\n(Click thumbnail to open full-size; click ✕ to mark Not relevant)`}
                className="block w-full h-full"
              >
                <img
                  src={p.url}
                  alt={p.summary}
                  loading="lazy"
                  className="w-full h-full object-contain"
                />
                <div className="absolute inset-x-0 bottom-0 z-10 translate-y-full group-hover/refimg:translate-y-0 transition-transform bg-black/85 text-white text-[10px] leading-snug px-2 py-1.5 pointer-events-none">
                  <div className="line-clamp-3">{p.summary}</div>
                </div>
              </a>
              {/* "Not relevant" button — hides this photo locally without
                  re-running the matcher. Persisted per case. */}
              <button
                type="button"
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  const next = new Set(hiddenUrls);
                  next.add(p.url);
                  persist(next);
                }}
                className="absolute top-1 right-1 z-20 inline-flex items-center gap-1 rounded-md bg-destructive/90 hover:bg-destructive text-white text-[10px] font-medium px-1.5 py-0.5 shadow-sm opacity-0 group-hover/refimg:opacity-100 transition-opacity"
                title="Hide this photo from this case (you can unhide via Reset)"
              >
                <X className="h-3 w-3" />
                Not relevant
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function CaseDetailDialog({
  entry,
  open,
  onOpenChange,
}: {
  entry: CaseEntry | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  if (!entry) return null;

  // Build a one-paragraph TL;DR that turns the structured fields into a
  // story an FC can grasp before they read the full case write-up. Format:
  //   "A [prospect] who already had [titleNoun]. We ran [play],
  //    structured as [anchor]. Outcome: [headline]."
  const titleNoun = prospectFromTitle(entry.title);
  const playPhrase = playInSentence(entry.play);
  const tldr = `A ${entry.prospect.toLowerCase()} — ${titleNoun}. The move: ${playPhrase}, structured as ${entry.anchor}. The numbers landed at ${entry.headline}.`;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[88vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2 mb-1">
            <Badge className="bg-primary/10 text-primary border-primary/20 font-mono">
              Case {entry.code}
            </Badge>
            <Badge variant="outline" className="text-xs">
              {CASE_PRODUCTS[entry.product].label}
            </Badge>
          </div>
          <DialogTitle className="text-lg leading-snug pr-8">
            {entry.title}
          </DialogTitle>
          <DialogDescription className="sr-only">
            {entry.headline}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 mt-2">
          {/* TL;DR — plain-English summary built from the structured fields
              so an FC opening this card immediately understands what the
              case is about without needing to decode the title and codes. */}
          <div className="rounded-xl bg-muted/40 border border-border/60 p-4">
            <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
              In plain English
            </div>
            <p className="text-sm leading-relaxed">{tldr}</p>
          </div>

          {/* Outcome callout — the headline number comparison */}
          <div className="rounded-xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900/50 p-4">
            <div className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-400 uppercase tracking-wide mb-1">
              The outcome (vs the prospect's existing setup)
            </div>
            <div className="text-sm text-emerald-900 dark:text-emerald-200 leading-relaxed font-medium">
              {entry.headline}
            </div>
          </div>

          {/* Metadata grid — kept for reference but compact */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
            <div>
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-0.5">
                Who they were
              </div>
              <div className="text-foreground">{entry.prospect}</div>
            </div>
            <div>
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-0.5">
                Play used
              </div>
              <div className="text-foreground">{entry.play}</div>
            </div>
            <div className="sm:col-span-2">
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-0.5">
                The deal shape (ticket size × duration)
              </div>
              <div className="text-foreground">{entry.anchor}</div>
            </div>
          </div>

          {/* Screenshot if present */}
          {entry.screenshot && (
            <div>
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
                Field receipt (real screenshot from the case)
              </div>
              <img
                src={entry.screenshot}
                alt={`${entry.title} — field receipt`}
                loading="lazy"
                className="w-full rounded-lg border bg-muted/20"
              />
            </div>
          )}

          {/* Auto-suggested reference photos — drawings/screenshots from the
              Telegram case-study chat whose context matches this case's
              product mentions + dollar amounts. Strong-signal only; the
              matcher refuses to fall back to generic play/tag overlap.
              The "Not relevant" button per photo writes to localStorage
              so wrong matches can be hidden without re-running the matcher. */}
          <CaseReferencePhotos caseId={entry.id} />

          {/* Drawings used */}
          {entry.drawings.length > 0 && (
            <div>
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
                Drawings used in this close — click to drill
              </div>
              <div className="flex flex-wrap gap-1.5">
                {entry.drawings.map((d) => (
                  <Link
                    key={d}
                    to={`/concept-cards?q=${encodeURIComponent(d)}`}
                    className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-primary/10 hover:bg-primary/20 text-primary text-xs font-medium border border-primary/20 transition-colors"
                  >
                    <Pencil className="h-3 w-3" />
                    {d}
                  </Link>
                ))}
              </div>
            </div>
          )}

          {/* Tags */}
          {entry.tags.length > 0 && (
            <div>
              <div className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
                Tags
              </div>
              <div className="flex flex-wrap gap-1">
                {entry.tags.map((t) => (
                  <Badge key={t} variant="outline" className="text-[10px]">
                    {t}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </div>

        <DialogFooter className="mt-4 flex-col sm:flex-row sm:justify-between gap-2">
          <Button
            variant="outline"
            size="sm"
            asChild
            className="gap-1.5"
          >
            <Link to="/concept-cards">
              <Pencil className="h-4 w-4" />
              Open Concept Cards
            </Link>
          </Button>
          <Button size="sm" asChild className="gap-1.5">
            <Link to={entry.sourcePath}>
              Read full case
              <ExternalLink className="h-4 w-4" />
            </Link>
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Page ───────────────────────────────────────────────────────────────
export default function CaseVaultPage() {
  const [search, setSearch] = useState("");
  const [filterProduct, setFilterProduct] = useState<string>("All");
  const [filterPlay, setFilterPlay] = useState<string>("All");
  const [selected, setSelected] = useState<CaseEntry | null>(null);
  const [detailOpen, setDetailOpen] = useState(false);
  const [searchParams, setSearchParams] = useSearchParams();

  // Auto-open a case if the URL has `?case=<id>` (e.g. from a deep-link
  // inside day-05.md "Open in Case Vault" badges).
  useEffect(() => {
    const caseId = searchParams.get("case");
    if (!caseId) return;
    const entry = CASES.find((c) => c.id === caseId);
    if (entry) {
      setSelected(entry);
      setDetailOpen(true);
    }
  }, [searchParams]);

  // When the dialog closes, strip the case= param so a refresh doesn't re-open.
  const handleDialogChange = (open: boolean) => {
    setDetailOpen(open);
    if (!open && searchParams.has("case")) {
      searchParams.delete("case");
      setSearchParams(searchParams, { replace: true });
    }
  };

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return CASES.filter((c) => {
      if (filterProduct !== "All" && c.product !== filterProduct) return false;
      if (filterPlay !== "All" && c.play !== filterPlay) return false;
      if (!q) return true;
      const hay = `${c.code} ${c.title} ${c.prospect} ${c.anchor} ${c.headline} ${c.tags.join(" ")} ${c.drawings.join(" ")}`.toLowerCase();
      return hay.includes(q);
    });
  }, [search, filterProduct, filterPlay]);

  const productCounts = useMemo(() => {
    const counts: Record<string, number> = { All: CASES.length };
    for (const c of CASES) {
      counts[c.product] = (counts[c.product] || 0) + 1;
    }
    return counts;
  }, []);

  const openCase = (entry: CaseEntry) => {
    setSelected(entry);
    setDetailOpen(true);
  };

  return (
    <PageLayout
      title="Case Vault — FINternship"
      description="31 real-prospect case studies across 7 AIA products — receipts, anchors, and the drawings that closed them."
    >
      <BrandedPageHeader
        tone="dark"
        showOnMobile
        title="Case Vault"
        subtitle="Real-prospect receipts across all 7 AIA products. Filter by product or play, click any card for the full close."
        breadcrumbs={[{ label: "Home", href: "/" }, { label: "Case Vault" }]}
        headerTabs={<ScriptsHubHeaderTabs />}
      />

      <div className="mx-auto px-3 md:px-6 py-3 md:py-8 max-w-6xl overflow-x-hidden">
        {/* Toolbar */}
        <div className="flex flex-col gap-2 mb-5">
          <div className="relative flex-1 min-w-0">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search by prospect, product, headline, drawing used..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>

          <div className="flex flex-wrap gap-2">
            <Select value={filterProduct} onValueChange={setFilterProduct}>
              <SelectTrigger className="w-[150px] sm:w-44 text-xs h-9">
                <span className="text-muted-foreground mr-1">Product:</span>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {PRODUCT_FILTER_OPTIONS.map((p) => (
                  <SelectItem key={p} value={p}>
                    {p === "All" ? "All products" : CASE_PRODUCTS[p].label} (
                    {productCounts[p] || 0})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={filterPlay} onValueChange={setFilterPlay}>
              <SelectTrigger className="w-[170px] sm:w-56 text-xs h-9">
                <span className="text-muted-foreground mr-1">Play:</span>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {PLAY_FILTER_OPTIONS.map((p) => (
                  <SelectItem key={p} value={p}>
                    {p === "All" ? "All plays" : p}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {(search || filterProduct !== "All" || filterPlay !== "All") && (
              <Button
                variant="ghost"
                size="sm"
                className="h-9"
                onClick={() => {
                  setSearch("");
                  setFilterProduct("All");
                  setFilterPlay("All");
                }}
              >
                Clear
              </Button>
            )}
          </div>

          <div className="text-xs text-muted-foreground">
            Showing {filtered.length} of {CASES.length} cases
          </div>
        </div>

        {/* Grid */}
        {filtered.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-border/60 bg-muted/20 p-10 text-center">
            <p className="text-sm text-muted-foreground">
              No cases match the current filters.
            </p>
          </div>
        ) : (
          <div
            className={cn(
              "grid gap-3 md:gap-4",
              "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"
            )}
          >
            {filtered.map((entry) => (
              <CaseCard key={entry.id} entry={entry} onOpen={openCase} />
            ))}
          </div>
        )}
      </div>

      <CaseDetailDialog
        entry={selected}
        open={detailOpen}
        onOpenChange={handleDialogChange}
      />
    </PageLayout>
  );
}
