// Build-time generator for the global search heading index.
// Run with bun (it imports the app's own parse pipeline so heading text goes
// through the exact transforms the renderer applies — no slug drift):
//   bun scripts/build-search-index.ts
// Regenerate after changing any day markdown file, then commit the output.
//
// Output: src/features/global-search/headingIndex.ts

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import GithubSlugger from "github-slugger";
import {
  parseFrontmatter,
  stripAppendix,
  convertWikilinks,
} from "../src/features/first-60-days/parse";
import {
  parseFrontmatter as parseF14Frontmatter,
  stripAppendix as stripF14Appendix,
} from "../src/features/first-14-days/parse";

type Track = "f60" | "pm" | "n60" | "f14";

interface TrackConfig {
  track: Track;
  dir: string;
  // Mirror each track's content.ts markdown pipeline (minus image embeds,
  // which never appear inside headings).
  transform: (body: string) => string;
}

const ROOT = join(import.meta.dir, "..");

const TRACKS: TrackConfig[] = [
  {
    track: "f60",
    dir: "docs/first-60-days",
    transform: (b) => convertWikilinks(stripAppendix(b)),
  },
  {
    track: "pm",
    dir: "docs/product-mastery-track",
    transform: (b) => stripAppendix(b),
  },
  {
    track: "n60",
    dir: "docs/next-60-days",
    transform: (b) => convertWikilinks(stripAppendix(b)),
  },
  {
    track: "f14",
    dir: "docs/first-14-days",
    transform: (b) => stripF14Appendix(b),
  },
];

const DAY_FILE_RE = /^day-(\d+)\.md$/;
const HEADING_RE = /^(#{1,3})\s+(.+?)\s*#*\s*$/;

// Reduce a markdown heading line to the plain text ReactMarkdown renders —
// rehype-slug slugs the rendered textContent, so images drop to their alt,
// links drop to their label, and inline formatting markers disappear.
// IMPORTANT: internal whitespace is preserved for the slug source — markdown
// keeps runs of spaces inside a text node, and github-slugger turns each
// space into a hyphen ("a  b" -> "a--b"). Collapsing before slugging produced
// anchors the renderer never emits. Only the display text is collapsed.
function headingText(raw: string): { display: string; slugSource: string } {
  const stripped = raw
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/(^|\s)_([^_]+)_(?=\s|$)/g, "$1$2")
    .replace(/~~([^~]+)~~/g, "$1")
    .replace(/<[^>]+>/g, "");
  return {
    display: stripped.replace(/\s+/g, " ").trim(),
    slugSource: stripped.trim(),
  };
}

// [track, day, level, text, slug]
type Row = [Track, number, number, string, string];

const rows: Row[] = [];

for (const cfg of TRACKS) {
  const trackDir = join(ROOT, cfg.dir);
  const weekDirs = readdirSync(trackDir).filter((d) => /^week-\d+$/.test(d));
  for (const week of weekDirs) {
    const weekPath = join(trackDir, week);
    for (const file of readdirSync(weekPath)) {
      const m = file.match(DAY_FILE_RE);
      if (!m) continue;
      const day = Number(m[1]);
      const raw = readFileSync(join(weekPath, file), "utf8");
      const parsed =
        cfg.track === "f14" ? parseF14Frontmatter(raw) : parseFrontmatter(raw);
      const body = cfg.transform(parsed.body);

      // One slugger per document — rehype-slug de-duplicates repeated heading
      // text per page (foo, foo-1, ...), and so must we.
      const slugger = new GithubSlugger();
      let inFence = false;
      for (const line of body.split("\n")) {
        if (/^\s*(```|~~~)/.test(line)) {
          inFence = !inFence;
          continue;
        }
        if (inFence) continue;
        const h = line.match(HEADING_RE);
        if (!h) continue;
        const { display, slugSource } = headingText(h[2]);
        if (!display) continue;
        const slug = slugger.slug(slugSource);
        rows.push([cfg.track, day, h[1].length, display, slug]);
      }
    }
  }
}

rows.sort((a, b) => a[0].localeCompare(b[0]) || a[1] - b[1]);

const counts = TRACKS.map(
  (t) => `${t.track}: ${rows.filter((r) => r[0] === t.track).length}`,
).join(", ");

const out = `// AUTO-GENERATED by scripts/build-search-index.ts. Do not edit by hand.
// Regenerate after changing day markdown files: bun scripts/build-search-index.ts
// Rows: ${rows.length} (${counts})

export type HeadingTrack = "f60" | "pm" | "n60" | "f14";

/** [track, dayNumber, headingLevel, renderedText, rehypeSlugAnchor] */
export type HeadingRow = [HeadingTrack, number, number, string, string];

export const HEADING_INDEX: HeadingRow[] = ${JSON.stringify(rows, null, 0).replace(/\],\[/g, "],\n[")};
`;

const outPath = join(ROOT, "src/features/global-search/headingIndex.ts");
writeFileSync(outPath, out);
console.log(`Wrote ${rows.length} headings (${counts}) -> ${outPath}`);
