/**
 * Generates a SQL migration file that bakes the current learning track seed
 * (phases + items + content blocks) into a Postgres function
 * `public.seed_learning_track()`.
 *
 * The function is idempotent: clears existing rows, re-inserts from a hardcoded
 * payload. Lovable applies the migration once; future re-seeds are just
 * `SELECT seed_learning_track();` in the SQL editor.
 *
 * Run:
 *   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
 *   node_modules/.bin/tsx scripts/generate-seed-migration.ts
 */
/* eslint-disable no-console */
import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const sb = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

/** Escape a value for SQL embedding. */
function sqlVal(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v)) {
    if (v.length === 0) return "ARRAY[]::text[]";
    const inner = v.map((x) => `'${String(x).replace(/'/g, "''")}'`).join(",");
    return `ARRAY[${inner}]::text[]`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  console.log("Pulling current seed state from Supabase...");

  const { data: phases, error: pErr } = await sb
    .from("learning_track_phases")
    .select("id, track, order_index, title, description")
    .order("track")
    .order("order_index");
  if (pErr) throw pErr;
  if (!phases?.length) throw new Error("No phases in DB — run seed-learning-track first");

  const { data: items, error: iErr } = await sb
    .from("learning_track_items")
    .select("id, phase_id, order_index, title, description, objectives, action_items, requires_submission, legacy_id");
  if (iErr) throw iErr;

  const { data: blocks, error: bErr } = await sb
    .from("learning_track_content_blocks")
    .select("item_id, order_index, block_type, title, body, url, resource_type, resource_id")
    .order("order_index");
  if (bErr) throw bErr;

  console.log(`  ${phases.length} phases, ${items?.length ?? 0} items, ${blocks?.length ?? 0} content blocks`);

  const phaseById = new Map(phases.map((p: any) => [p.id as string, p]));
  const itemById = new Map((items ?? []).map((i: any) => [i.id as string, i]));

  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  push("-- Seed learning track phases, items, and content blocks.");
  push("-- Generated by scripts/generate-seed-migration.ts from the live DB state.");
  push("-- Idempotent: re-run with SELECT public.seed_learning_track(); any time.");
  push("");
  push("CREATE OR REPLACE FUNCTION public.seed_learning_track()");
  push("RETURNS void");
  push("LANGUAGE plpgsql");
  push("SECURITY DEFINER");
  push("SET search_path = public");
  push("AS $seed$");
  push("DECLARE");
  push("  v_phase_id uuid;");
  push("  v_item_id  uuid;");
  push("BEGIN");
  push("  -- Clear existing (cascades through items -> content_blocks)");
  push("  DELETE FROM public.learning_track_phases;");
  push("");

  for (const p of phases) {
    push(`  -- Phase: ${p.track} / ${p.order_index} / ${p.title}`);
    push(
      `  INSERT INTO public.learning_track_phases (track, order_index, title, description) VALUES (${sqlVal(p.track)}, ${sqlVal(p.order_index)}, ${sqlVal(p.title)}, ${sqlVal(p.description)}) RETURNING id INTO v_phase_id;`
    );

    const phaseItems = (items ?? [])
      .filter((i: any) => i.phase_id === p.id)
      .sort((a: any, b: any) => a.order_index - b.order_index);

    for (const i of phaseItems) {
      push(
        `  INSERT INTO public.learning_track_items (phase_id, order_index, title, description, objectives, action_items, requires_submission, legacy_id) VALUES (v_phase_id, ${sqlVal(i.order_index)}, ${sqlVal(i.title)}, ${sqlVal(i.description)}, ${sqlVal(i.objectives)}, ${sqlVal(i.action_items)}, ${sqlVal(i.requires_submission)}, ${sqlVal(i.legacy_id)}) RETURNING id INTO v_item_id;`
      );

      const itemBlocks = (blocks ?? [])
        .filter((b: any) => b.item_id === i.id)
        .sort((a: any, b: any) => a.order_index - b.order_index);

      for (const b of itemBlocks) {
        push(
          `  INSERT INTO public.learning_track_content_blocks (item_id, order_index, block_type, title, body, url, resource_type, resource_id) VALUES (v_item_id, ${sqlVal(b.order_index)}, ${sqlVal(b.block_type)}, ${sqlVal(b.title)}, ${sqlVal(b.body)}, ${sqlVal(b.url)}, ${sqlVal(b.resource_type)}, ${sqlVal(b.resource_id)});`
        );
      }
    }
    push("");
  }

  push("END;");
  push("$seed$;");
  push("");
  push("-- Apply the seed once at migration time");
  push("SELECT public.seed_learning_track();");
  push("");

  const ts = new Date()
    .toISOString()
    .replace(/[-:T]/g, "")
    .slice(0, 14);
  const filename = `${ts}_seed_learning_track_function.sql`;
  const path = join("supabase", "migrations", filename);
  writeFileSync(path, lines.join("\n"));
  console.log(`\nWrote ${path} (${lines.length} lines)`);
  console.log(`To re-seed any time: SELECT public.seed_learning_track();`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
