-- Create user@demo.com account
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_sent_at,
  recovery_token,
  reauthentication_token,
  reauthentication_sent_at,
  is_super_admin,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_new,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  invited_at,
  confirmation_sent_at,
  deleted_at,
  is_sso_user,
  is_anonymous
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'b0e2c3d4-e5f6-7890-abcd-ef1234567890',
  'authenticated',
  'authenticated',
  'user@demo.com',
  crypt('demo123456', gen_salt('bf')),
  NOW(),
  NULL,
  NULL,
  '{"provider": "email", "providers": ["email"]}',
  '{"display_name": "Demo User"}',
  NOW(),
  NOW(),
  '',
  '',
  NULL,
  '',
  '',
  NULL,
  false,
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  '',
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  false
);

-- Create profile for user@demo.com
INSERT INTO public.profiles (user_id, email, display_name, first_name, last_name)
VALUES (
  'b0e2c3d4-e5f6-7890-abcd-ef1234567890',
  'user@demo.com',
  'Demo User',
  'Demo',
  'User'
);

-- Assign user role to user@demo.com
INSERT INTO public.user_roles (user_id, role)
VALUES ('b0e2c3d4-e5f6-7890-abcd-ef1234567890', 'user');