INSERT INTO public.question_bank_questions
(product_slug, bank_type, category, question, options, correct_answer, explanation, sort_order)
VALUES
-- Suitability (6) — study
('pro-lifetime-protector','study','suitability','A 35-year-old sole breadwinner with two young children and a mortgage wants the cheapest cover possible. Why might Pro Lifetime Protector still be worth a serious conversation, even if term seems cheaper at first glance?','["Because PLP guarantees better investment returns than term + invest the difference","Because PLP combines lifetime protection with a flexible investment account, which can be useful when dependants'' need for cover may extend well beyond a typical term policy","Because term plans cannot cover critical illness","Because PLP is always cheaper than term in the long run"]'::jsonb, 1, 'PLP is a hybrid ILP — it pairs whole-of-life protection with an investment account. For a sole breadwinner whose protection horizon is uncertain (children to adulthood, mortgage, dependants for life), the lifetime nature and flexibility can justify the higher cost. Avoid claiming guaranteed returns or that term cannot include CI riders.', 120),
('pro-lifetime-protector','study','suitability','Which client profile is LEAST suitable for Pro Lifetime Protector?','["A 30-year-old professional with stable income looking for long-term protection plus investment exposure","A 45-year-old business owner with surplus cash flow seeking flexible long-term coverage","A 28-year-old contract worker with irregular income who needs maximum protection at the lowest possible premium for the next 10 years","A young parent who wants permanent CI cover with the option to grow cash value"]'::jsonb, 2, 'PLP is a long-term commitment with regular premium obligations. A client with irregular income whose primary need is maximum cover at lowest cost for a defined period is far better served by a term plan. Suitability is about matching the structure to the client''s cash flow stability and time horizon, not just the protection amount.', 121),
('pro-lifetime-protector','study','suitability','When assessing PLP suitability, which combination of factors should weigh MOST heavily in your recommendation?','["The size of the welcome bonus and booster units","Time horizon, premium sustainability, protection need permanence, and risk tolerance for the underlying funds","The fund''s past 1-year performance","The client''s preference for monthly vs annual premium mode"]'::jsonb, 1, 'PLP suitability is driven by structural fit: how long protection is needed, whether premiums can be sustained, whether the client accepts investment risk on the cash value, and whether the protection need is permanent. Bonuses and short-term performance are secondary.', 122),
('pro-lifetime-protector','study','suitability','A client says: I want PLP because my friend got 8% returns last year. What is the strongest suitability response?','["Confirm the 8% as a realistic expectation","Reset expectations: ILP returns depend on chosen funds and market conditions, are not guaranteed, and PLP should be evaluated primarily on protection fit, not on a single year''s performance","Switch to a higher-risk fund to chase similar returns","Recommend a single premium top-up immediately"]'::jsonb, 1, 'Suitability and compliance overlap here. You must reset performance expectations, anchor the conversation on protection fit and long-term planning, and avoid letting recency bias drive product selection. Past performance is not indicative of future results.', 123),
('pro-lifetime-protector','study','suitability','A 55-year-old client with an 8-year horizon to retirement asks about PLP for wealth accumulation. What is the best suitability stance?','["Recommend PLP as a primary accumulation tool","Decline the sale outright","Acknowledge that PLP is structured for long-term protection with investment, not short-horizon accumulation; explore whether a permanent protection need exists, and if not, consider more appropriate solutions","Recommend the highest sum assured to maximise charges absorbed by the booster"]'::jsonb, 2, 'ILP charges (especially insurance charges at older ages) and short horizons make PLP a poor pure-accumulation vehicle near retirement. The right move is to clarify whether there is a real, permanent protection need; if not, redirect to suitable alternatives.', 124),
('pro-lifetime-protector','study','suitability','How should an advisor frame the trade-off between sum assured and investment growth inside PLP?','["Maximise sum assured to maximise commission","Maximise investment allocation and minimise sum assured","Explain that higher sum assured means higher insurance charges deducted from units, which reduces investible value, and calibrate the balance to the client''s actual protection need","Tell the client the two are independent"]'::jsonb, 2, 'A core PLP concept: insurance charges are deducted from units monthly and rise with age. Over-insuring drains the investment side; under-insuring leaves the family exposed. Advisors must calibrate sum assured to genuine need, not to maximise either side.', 125),

-- Compliance (6) — study
('pro-lifetime-protector','study','compliance','Which statement about PLP is MOST compliant?','["This plan guarantees lifetime protection regardless of fund performance","Cash value and sustainability of cover depend on fund performance, charges, and premium continuation, and are not guaranteed","Your unit value will only go up over time","The booster ensures you cannot lose money"]'::jsonb, 1, 'ILPs carry investment risk. Cover sustainability depends on whether the unit account can absorb rising insurance charges. Advisors must clearly state that cash value and the duration of cover are not guaranteed.', 126),
('pro-lifetime-protector','study','compliance','A client asks: If markets crash, will my PLP cover still continue? What is the best response?','["Yes, cover is guaranteed for life regardless of market","No, cover lapses immediately on a market drop","Cover continues as long as the unit account can sustain monthly insurance charges; sustained underperformance plus rising charges with age may erode units, so reviews are important","The booster will always top up any losses"]'::jsonb, 2, 'The mortality/insurance charge model is central to ILP compliance. You must explain the lapse risk if units deplete, especially at older ages when charges rise sharply, and the role of regular reviews and top-ups.', 127),
('pro-lifetime-protector','study','compliance','Under needs-based selling rules, what is the FIRST step before recommending PLP?','["Quote a premium based on the client''s budget","Conduct a fact-find to understand objectives, financial situation, dependants, existing coverage, time horizon, and risk profile","Show the highest-performing fund factsheet","Present the welcome bonus"]'::jsonb, 1, 'Needs-based selling: fact-find first, then needs analysis, then recommendation with documented basis. Skipping this is a compliance breach.', 128),
('pro-lifetime-protector','study','compliance','Which claim about PLP boosters and welcome bonus is NOT compliant?','["Boosters add extra units in early policy years subject to terms","Boosters are subject to a recovery or clawback if the policy is terminated within a stipulated period","Boosters guarantee positive returns in early years","Boosters are funded from the insurer''s structure, not from guaranteed market gains"]'::jsonb, 2, 'Boosters add units, but unit value still moves with markets. Saying boosters guarantee positive returns is misleading. Always describe boosters as additional unit allocations subject to recovery terms, not as a return guarantee.', 129),
('pro-lifetime-protector','study','compliance','A client asks you to just sign here and let you fill in the rest. What must you do?','["Accept to save time","Decline politely and complete the fact-find and forms together with the client, ensuring the client understands and signs each material section themselves","Sign on the client''s behalf with verbal consent","Backdate the form"]'::jsonb, 1, 'Pre-signed or advisor-completed forms are serious compliance breaches and a common disciplinary trigger. The client must complete and sign material declarations themselves, with the advisor explaining each section.', 130),
('pro-lifetime-protector','study','compliance','How should you compare PLP against a competitor''s ILP in client meetings?','["Use selective figures that favour PLP","Disparage the competitor''s claims record","Compare like-for-like features (charges, fund range, riders, flexibility) using approved materials, and disclose limitations on both sides","Promise to beat any competitor''s illustration"]'::jsonb, 2, 'Compliant competitive selling uses approved, factual, like-for-like comparisons. Cherry-picking, disparagement, or promising to beat illustrations is non-compliant.', 131),

-- Advisory Skills (6) — study
('pro-lifetime-protector','study','advisory-skills','What is the strongest opening discovery question before introducing PLP?','["Do you want the dividend or growth fund?","How much can you invest each month?","If something happened to you tomorrow, what would you want your family''s financial picture to look like 1, 5, and 20 years out?","Which booster option do you prefer?"]'::jsonb, 2, 'Great advisors open with future-state, emotion-anchored questions that surface real protection and legacy needs. Product-feature questions belong much later in the conversation.', 132),
('pro-lifetime-protector','study','advisory-skills','A client''s spouse keeps interrupting with objections. What is the best advisory move?','["Ignore the spouse and continue","Pause, acknowledge the spouse''s concerns, and invite them into the discovery process as a co-decision-maker","Ask the spouse to leave","Push to close before more objections"]'::jsonb, 1, 'In couples or family decisions, the silent or interrupting partner is often the real decision-maker. Bringing them into discovery as a partner improves trust and conversion.', 133),
('pro-lifetime-protector','study','advisory-skills','When explaining PLP charges to a non-technical client, what is the BEST approach?','["Skip charges to avoid confusion","Use a simple analogy (e.g. every month a small slice of your units pays for the protection, like a subscription) then walk through the benefit illustration line by line","Read the BI verbatim","Tell them charges don''t really matter long-term"]'::jsonb, 1, 'Strong advisors use plain-language analogies for complex mechanics, then anchor the analogy to the actual BI numbers so the client understands AND has documented disclosure.', 134),
('pro-lifetime-protector','study','advisory-skills','Mid-presentation a client says, I''m getting confused. What should you do?','["Push through to finish","Stop, summarise the last point in one sentence, and ask which part is unclear before continuing","Hand them the brochure","Reschedule"]'::jsonb, 1, 'Confusion is a buying signal blocker. Pausing, summarising, and clarifying restores trust and momentum. Pushing through erodes both.', 135),
('pro-lifetime-protector','study','advisory-skills','A client says: I''ll think about it and get back to you. What is the most advanced response?','["Wait for them to call","Acknowledge, then ask: just so I can prepare better for our next chat, is it the protection amount, the premium, the investment side, or something else you''d like to think through?","Pressure for a decision now","Send a follow-up brochure only"]'::jsonb, 1, 'Skilled advisors convert vague stalls into specific, addressable concerns. The clarifying question reframes think about it into a concrete, scheduled next step.', 136),
('pro-lifetime-protector','study','advisory-skills','Which behaviour BEST distinguishes a top 1% advisor presenting PLP?','["Memorising every fund factsheet","Connecting product features to the client''s specific life events and decisions, and being willing to recommend AGAINST PLP when it doesn''t fit","Quoting the highest sum assured","Closing in one meeting"]'::jsonb, 1, 'Top advisors are trusted because they are willing to walk away from unsuitable sales. Specificity to the client''s life and intellectual honesty drive long-term referrals.', 137),

-- Closing (6) — study
('pro-lifetime-protector','study','closing','A client says: The premium is a bit higher than I expected. What is the best advanced close?','["Drop the sum assured immediately","Explore: is it cash flow, perceived value, or comparison-driven? Then restructure (premium term, sum assured, riders) to match true affordability without dropping the protection floor","Push original quote harder","End the meeting"]'::jsonb, 1, 'Premium objections almost always mask a deeper concern (cash flow, value perception, or competitor comparison). Diagnosing first and restructuring intelligently outperforms reflex discounting.', 138),
('pro-lifetime-protector','study','closing','A client says: Let me check with my financial planner first. Best response?','["Discourage the second opinion","Welcome it, offer to share your fact-find and BI for transparent review, and propose a follow-up date","Drop the case","Push to close before they consult"]'::jsonb, 1, 'Confident advisors welcome scrutiny — it builds trust and signals nothing to hide. Setting the follow-up date keeps momentum.', 139),
('pro-lifetime-protector','study','closing','How do you handle: I want to wait until next year''s bonus to decide?','["Agree and wait","Quantify the cost of delay: 1 year of protection foregone, potential premium increase due to age, and underwriting risk if health changes","Pressure with scarcity","Drop the case"]'::jsonb, 1, 'Effective closing on delay objections quantifies the real cost: a year of unprotected exposure, age-banded premium step-up, and insurability risk. This reframes waiting as an active decision with consequences.', 140),
('pro-lifetime-protector','study','closing','A client is about to sign but suddenly hesitates. What is the best advanced move?','["Push the pen forward","Pause, ask what''s coming up for you right now and listen fully before responding","Restate the close","Joke to ease tension"]'::jsonb, 1, 'Last-second hesitation almost always signals one unresolved concern. A non-pressured open question surfaces it; only then can you address it cleanly.', 141),
('pro-lifetime-protector','study','closing','Which is the MOST sustainable closing philosophy for PLP?','["Close every prospect","Close only when the recommendation is genuinely the best fit and the client has informed consent, even if that means recommending term + invest separately","Close on emotion only","Close on price only"]'::jsonb, 1, 'PLP closures are long-term, high-trust commitments. Closing only well-fitted cases protects the advisor''s persistency, reputation, and referral pipeline. Misfit closes return as lapses, complaints, or lost clients.', 142),
('pro-lifetime-protector','study','closing','After the close, what action best protects both client and advisor?','["Move on to the next prospect","Schedule a 30-day check-in and an annual review, document understanding in writing, and confirm free-look period implications","Wait for the client to call","Send only a thank-you message"]'::jsonb, 1, 'Post-sale service is part of closing well. Documented check-ins, annual reviews, and free-look explanation reduce buyer''s remorse, lapses, and complaints.', 143),

-- ============================================================
-- EXAM BANK: 20 advanced questions (sort_order 36-55)
-- ============================================================
('pro-lifetime-protector','exam','suitability','Which client is MOST suitable for Pro Lifetime Protector?','["A retiree wanting guaranteed yearly payouts","A 30-year-old with stable income, long-term protection need, and willingness to accept investment risk on the cash value","A client needing capital back in 18 months","A client with no protection need but wanting pure investment"]'::jsonb, 1, 'PLP fits clients with permanent protection need, long horizon, sustainable premium capacity, and acceptance of investment risk. Short horizons or pure investment goals are mismatched.', 36),
('pro-lifetime-protector','exam','suitability','A client''s income is highly variable. Which is the MOST appropriate suitability action for a PLP recommendation?','["Recommend the maximum sum assured","Stress-test premium affordability against the client''s lowest realistic income period and consider lower commitment or alternative structures","Push the highest welcome bonus tier","Defer all underwriting questions"]'::jsonb, 1, 'PLP requires sustained premium payment. Stress-testing affordability against worst-case cash flow is core advanced suitability practice for variable-income clients.', 37),
('pro-lifetime-protector','exam','suitability','Why is permanent protection need a key suitability criterion for PLP?','["Because PLP is a single premium product","Because PLP is designed to provide lifetime cover, so a client who only needs protection for a defined period (e.g. 20 years) is usually better served by term","Because PLP guarantees returns","Because PLP cannot be surrendered"]'::jsonb, 1, 'PLP''s structural value is lifetime cover plus investment. Time-bound needs (e.g. mortgage period, dependants until age 25) often suit term better and at lower cost.', 38),
('pro-lifetime-protector','exam','suitability','A client wants high investment growth and minimal protection. What is the most suitable action?','["Sell PLP with minimum sum assured","Recognise the mismatch — pure investment goals are usually better served by investment-only solutions; recommend PLP only if a real protection need exists","Maximise the booster only","Skip suitability and proceed"]'::jsonb, 1, 'PLP without genuine protection need turns insurance charges into pure drag on investment performance. Suitability requires acknowledging the mismatch.', 39),
('pro-lifetime-protector','exam','suitability','When is PLP LEAST suitable?','["When the client has dependants and wants permanent cover","When the client needs liquid capital within 1-3 years for a planned expense","When the client wants protection plus market-linked growth","When the client has stable long-term income"]'::jsonb, 1, 'Surrender values in early years are typically low due to charges and unit deduction. Capital needed in 1-3 years should not be parked in PLP.', 40),

('pro-lifetime-protector','exam','compliance','Which statement about PLP is compliant?','["Returns are guaranteed at 5% per year","Cover continues as long as the unit account can pay monthly charges; cash value depends on fund performance","Boosters guarantee profit","You cannot lose money in this plan"]'::jsonb, 1, 'Compliant disclosure must reflect the ILP mechanics: charges deducted from units, no return guarantees, lapse risk if units deplete.', 41),
('pro-lifetime-protector','exam','compliance','What MUST be disclosed when recommending PLP?','["Only the upside scenarios","Charges, risks, fund objectives, surrender value pattern, premium term, and that returns are not guaranteed","Only the welcome bonus","Only the advisor''s commission tier"]'::jsonb, 1, 'Material disclosure includes charges, risks, surrender value, premium obligations, and non-guaranteed nature of returns. Selective disclosure is a breach.', 42),
('pro-lifetime-protector','exam','compliance','A prospect asks you to recommend PLP without completing the fact-find. What must you do?','["Accept to keep the client happy","Decline and explain that a documented needs analysis is required before any recommendation","Recommend a small policy without fact-find","Pre-fill the fact-find later"]'::jsonb, 1, 'Needs-based selling rules require a documented fact-find before recommendation. No fact-find = no recommendation.', 43),
('pro-lifetime-protector','exam','compliance','Which behaviour is a clear compliance breach?','["Walking the client through the BI line by line","Recommending against PLP when unsuitable","Stating that boosters guarantee positive returns regardless of market","Comparing PLP to a competitor using approved materials"]'::jsonb, 2, 'Guarantee claims on market-linked components are misleading and a clear breach. Boosters add units; unit value is still market-linked.', 44),
('pro-lifetime-protector','exam','compliance','Free-look period under PLP allows the client to:','["Cancel anytime with full refund of premiums plus interest","Cancel within the stipulated free-look window and receive premiums refunded subject to terms (typically less any market value adjustment on units invested)","Cancel only if the advisor agrees","Switch funds without restriction"]'::jsonb, 1, 'Free-look is a regulated cooling-off period. Refund mechanics typically allow for adjustments related to unit value, and advisors must explain this clearly.', 45),

('pro-lifetime-protector','exam','advisory-skills','What is the BEST first discovery question before pitching PLP?','["Which fund do you prefer?","What protection do you currently have, and what would you want to be true for your family if something happened to you?","How much can you afford monthly?","Do you want the booster?"]'::jsonb, 1, 'Strong discovery anchors on existing coverage and desired family outcomes — surfacing genuine need rather than pre-empting product selection.', 46),
('pro-lifetime-protector','exam','advisory-skills','A client says, I don''t understand investment-linked plans. Best advisory move?','["Skip the investment portion","Use a clear analogy, walk through the BI together, and confirm understanding before continuing","Read the BI verbatim","Push to close anyway"]'::jsonb, 1, 'Translating complexity into clear analogies plus actual BI walkthrough is the hallmark of effective advisory communication.', 47),
('pro-lifetime-protector','exam','advisory-skills','A client raises a competitor product mid-presentation. What is the best response?','["Disparage the competitor","Acknowledge it, ask what attracted them to it, and offer a balanced like-for-like comparison","Refuse to discuss","Drop your case"]'::jsonb, 1, 'Confident, balanced engagement with competitors builds trust. Disparagement is both unprofessional and a compliance risk.', 48),
('pro-lifetime-protector','exam','advisory-skills','Which behaviour signals overselling?','["Asking deep discovery questions","Recommending the highest sum assured before understanding the client''s actual needs and cash flow","Walking through charges","Recommending against PLP when unsuitable"]'::jsonb, 1, 'Overselling = recommendation before discovery. The diagnostic order is: discover, then analyse, then recommend.', 49),
('pro-lifetime-protector','exam','advisory-skills','What MOST distinguishes a top advisor in PLP conversations?','["Always closing in one meeting","Linking product mechanics to the client''s specific life decisions, and being willing to recommend term + invest separately when more suitable","Selling the highest sum assured","Memorising fund returns"]'::jsonb, 1, 'Top advisors think client-first. Recommending an alternative when it fits better builds the trust that drives lifetime referrals.', 50),

('pro-lifetime-protector','exam','closing','A client says, Premium is too high. Best closing approach?','["Push the same plan harder","Diagnose the root cause (cash flow vs value vs comparison), then restructure premium term, sum assured, or riders to match real affordability","Drop the case","Offer an unauthorised discount"]'::jsonb, 1, 'Diagnosis-first closing protects the protection floor while addressing real affordability. Reflex discounting damages both case quality and persistency.', 51),
('pro-lifetime-protector','exam','closing','A client wants to consult their spouse. Best move?','["Close before they consult","Welcome it and arrange a joint meeting to walk through the recommendation together","Discourage the consultation","End the case"]'::jsonb, 1, 'Joint meetings improve clarity, reduce post-sale regret, and increase persistency. Excluding the spouse is a major risk factor.', 52),
('pro-lifetime-protector','exam','closing','How should you handle: I want to wait and see how markets perform?','["Agree and wait indefinitely","Reframe: protection should not be timed to markets, and delay carries insurability and age-banded premium risk","Drop the case","Pressure with scarcity"]'::jsonb, 1, 'Protection timing is independent of market timing. Highlighting age, health, and underwriting risk reframes waiting as a costly active decision.', 53),
('pro-lifetime-protector','exam','closing','At the close, the client suddenly goes quiet. What is the best move?','["Restate the close immediately","Pause, ask an open question to surface the unspoken concern, then address it before re-attempting close","Hand the pen over","End the meeting"]'::jsonb, 1, 'Silence at close = unresolved concern. Surfacing it with an open question is more effective than pressing forward.', 54),
('pro-lifetime-protector','exam','closing','Ultimate measure of a successful PLP close?','["Premium size","A well-fitted policy that the client understands, can sustain, and stays on the books for the long term","Speed of closure","Highest sum assured"]'::jsonb, 1, 'Persistency and client satisfaction — not premium size or closure speed — are the true markers of long-term advisory success.', 55);