INSERT INTO public.question_bank_questions
(product_slug, bank_type, category, question, options, correct_answer, explanation, sort_order)
VALUES
('healthshield-gold-max','study','suitability','A client earns well but says they are uncomfortable with rising premiums in later years. What is the best recommendation approach?','["Recommend Plan A immediately due to higher coverage","Focus only on current affordability","Discuss long-term premium sustainability and consider a plan that balances coverage and affordability","Recommend adding all riders to maximize value"]'::jsonb, 2, 'Hospital plans are long-term commitments with premiums increasing with age. A strong advisor considers not just current affordability but sustainability into older ages, helping the client choose a plan they are likely to maintain.', 120),
('healthshield-gold-max','study','suitability','A client insists on private hospital access but has limited disposable income. What is the best approach?','["Proceed with Plan A since it matches preference","Recommend Plan B or a downgraded option after explaining trade-offs","Push for Plan A and remove rider","Ignore affordability concerns"]'::jsonb, 1, 'Suitability requires balancing preferences with affordability. A plan that cannot be sustained may lead to lapse or downgrade later, which is not in the client''s long-term interest.', 121),
('healthshield-gold-max','study','suitability','A young client says: "I''m healthy, so I don''t think I need this yet." What is the best advisory perspective?','["Agree and defer discussion","Emphasize that underwriting becomes stricter with age and health changes","Push for immediate purchase without explanation","Focus only on MediShield Life"]'::jsonb, 1, 'The key concept is insurability risk. Health insurance is easier to secure when healthy, and delays may result in exclusions or higher costs later.', 122),
('healthshield-gold-max','study','suitability','Which client is least suitable for a full rider (e.g. VitalHealth)?','["Client seeking cost certainty","Client with stable income","Client highly sensitive to premium costs","Client with family dependents"]'::jsonb, 2, 'Riders increase premiums. If a client is highly cost-sensitive, adding a rider may not be sustainable, even if it improves claim experience.', 123),
('healthshield-gold-max','study','suitability','A client wants the highest coverage "just in case," but has no emergency savings. What should you do?','["Proceed with highest plan","Recommend a balanced plan and highlight importance of emergency funds","Ignore emergency fund issue","Sell rider only"]'::jsonb, 1, 'Insurance should complement financial planning, not replace it. Emergency liquidity remains essential even with strong coverage.', 124),
('healthshield-gold-max','study','compliance','A client asks: "Will this plan cover all my hospital bills?" What is the best response?','["Yes, fully covered","Yes, if you add a rider","Coverage depends on policy terms, limits, and conditions, including co-payment requirements","Only large bills are covered"]'::jsonb, 2, 'Full coverage cannot be guaranteed. All claims are subject to policy terms, deductibles, co-payments, and limits.', 125),
('healthshield-gold-max','study','compliance','Which statement is MOST appropriate under current MOH rider rules?','["The rider removes all out-of-pocket costs","The rider may reduce out-of-pocket costs, but you will still bear part of the bill, including the deductible","The rider guarantees zero payment","You will only pay for minor treatments"]'::jsonb, 1, 'Under current rules, riders cannot cover the minimum deductible and require co-payment. Advisors must set realistic expectations.', 126),
('healthshield-gold-max','study','compliance','A client asks if dividends or investments can fully fund future premiums. What is the best response?','["Yes, guaranteed","Possible but not guaranteed, depends on performance","Yes if long enough","No, never possible"]'::jsonb, 1, 'Financial strategies using investments are projections, not guarantees. Advisors must avoid overpromising outcomes.', 127),
('healthshield-gold-max','study','compliance','Which statement should be avoided?','["This helps manage large medical costs","Coverage is subject to limits and conditions","You will definitely never pay anything out of pocket","Let''s review your needs first"]'::jsonb, 2, 'Absolute guarantees are misleading and non-compliant.', 128),
('healthshield-gold-max','study','advisory-skills','A client compares insurers purely based on premium. What is the best approach?','["Compete on price","Reframe discussion to coverage, claims experience, and sustainability","Criticize competitors","Avoid comparison"]'::jsonb, 1, 'Good advisors shift focus from price to value, including coverage scope, claim support, and long-term sustainability.', 129),
('healthshield-gold-max','study','advisory-skills','A client is overwhelmed by plan options. What should you do?','["Show all options at once","Simplify by narrowing down based on needs","Push highest plan","Skip explanation"]'::jsonb, 1, 'Simplification helps decision-making. Overloading clients reduces clarity and trust.', 130),
('healthshield-gold-max','study','advisory-skills','A client asks: "Why do I need a rider?" What is the best explanation?','["It makes the plan more expensive","It helps reduce uncertainty in out-of-pocket costs","It is mandatory","It increases commission"]'::jsonb, 1, 'The value of a rider lies in improving cost predictability and reducing financial shock during claims.', 131),
('healthshield-gold-max','study','advisory-skills','What distinguishes a strong hospital plan advisor?','["Selling highest plan","Matching plan to client needs and financial situation","Closing quickly","Avoiding objections"]'::jsonb, 1, 'True advisory is about alignment, not maximization.', 132),
('healthshield-gold-max','study','advisory-skills','A client says: "I''ll just rely on MediShield Life." What is the best response?','["Agree","Explain coverage limitations and potential out-of-pocket exposure","Push aggressively","Ignore"]'::jsonb, 1, 'MediShield Life provides basic coverage but may leave significant gaps, especially for private care.', 133),
('healthshield-gold-max','study','closing','A client says: "I need time to think." What is best response?','["Wait silently","Clarify concerns and set a follow-up","Pressure to sign","End meeting"]'::jsonb, 1, 'Effective closing identifies and resolves hesitation rather than waiting passively.', 134),
('healthshield-gold-max','study','closing','A client says: "Premium is too high." What is best approach?','["Push harder","Explore alternative plans or structure","Ignore concern","End discussion"]'::jsonb, 1, 'Objection often reflects affordability mismatch — adjust solution instead of forcing.', 135),
('healthshield-gold-max','study','closing','Client wants to consult spouse. Best move?','["Push","Arrange joint meeting","Ignore","Close anyway"]'::jsonb, 1, 'Involving decision-makers improves clarity and conversion.', 136),
('healthshield-gold-max','study','closing','Client is interested but unsure. Best response?','["Pressure","Revisit needs and confirm fit","Ignore","Delay"]'::jsonb, 1, 'Uncertainty often comes from unclear fit — revisit fundamentals.', 137),
('healthshield-gold-max','study','roleplay','Client says: "I''ll just pay cash if anything happens." Best response?','["Agree","Highlight unpredictability and magnitude of medical costs","Push","Ignore"]'::jsonb, 1, 'Self-insurance may not be realistic for large medical bills.', 138),
('healthshield-gold-max','study','roleplay','Client says: "Insurance companies always reject claims." Best response?','["Promise all claims approved","Explain claims process, conditions, and how to improve approval chances","Avoid topic","Change subject"]'::jsonb, 1, 'Transparency builds trust. Avoid overpromising while educating properly.', 139);