
INSERT INTO public.question_bank_questions
(product_slug, bank_type, category, question, options, correct_answer, explanation, sort_order)
VALUES
-- ============ STUDY BANK (sort_order 120-143) ============
('ultimate-critical-cover','study','suitability','A 38-year-old sole breadwinner with a mortgage and two young kids asks about CI cover. Why is Ultimate Critical Cover (UCC) a strong fit?',
 '["Term CI provides high cover at affordable cost during peak liability years and supports income replacement on diagnosis","Whole-life is always better","CI is unnecessary if hospitalisation is in place","Endowment plans cover CI"]'::jsonb,
 0,'Term CI maximises sum assured per dollar during years when income loss has the largest financial impact (mortgage + dependants).',120),
('ultimate-critical-cover','study','suitability','Which client is LEAST suitable for UCC as a standalone CI solution?',
 '["A 35-year-old professional with no CI cover","A 70-year-old retiree wanting lifetime CI guarantee with no premium increases","A young parent with high mortgage","A self-employed professional"]'::jsonb,
 1,'Retirees needing guaranteed lifetime CI with level premiums are typically better served by whole-life CI.',121),
('ultimate-critical-cover','study','suitability','How should you size a CI sum assured for a 40-year-old earning $120k/year with a 20-year mortgage?',
 '["1x annual income","Use a needs-based approach: 3-5 years income replacement plus outstanding liabilities and treatment buffer","A flat $50,000","Match the spouse cover only"]'::jsonb,
 1,'CI sizing reflects recovery time, income replacement, debt clearance, and treatment costs.',122),
('ultimate-critical-cover','study','suitability','A client says "I have early CI cover under my hospital rider." Correct suitability response?',
 '["Agree it is enough","Clarify the rider scope, payout limits, and whether it covers income replacement vs medical costs — most riders are reimbursement-only","Cancel the rider","Sell another hospital plan"]'::jsonb,
 1,'Hospital riders typically reimburse medical costs only and do not provide lump-sum income replacement on CI diagnosis.',123),
('ultimate-critical-cover','study','suitability','When is multi-pay CI most suitable?',
 '["Never","For clients with family history of recurrence or multiple unrelated CI exposure who need protection beyond first claim","Only for retirees","Only for HNW clients"]'::jsonb,
 1,'Multi-pay structures protect against recurrence and unrelated CI events.',124),
('ultimate-critical-cover','study','suitability','A client wants the cheapest CI plan. Right suitability move?',
 '["Sell cheapest blindly","Right-size cover to genuine need within budget; explain trade-offs of lower SA vs early-stage gaps","Refuse to advise","Push the most expensive plan"]'::jsonb,
 1,'Affordability matters but advisor must explain coverage trade-offs.',125),
('ultimate-critical-cover','study','compliance','Under FAA, what must precede a UCC recommendation?',
 '["Just a signed application","Documented fact-find, basis of recommendation, and product disclosures including exclusions and waiting periods","Verbal agreement","Nothing"]'::jsonb,
 1,'MAS Notice FAA-N16 mandates documented suitability and disclosure for life-related products.',126),
('ultimate-critical-cover','study','compliance','A client conceals a prior cancer screening abnormality during underwriting. Correct action?',
 '["Submit anyway","Educate on duty of disclosure under the Insurance Act; non-disclosure may void claims; obtain proper declaration","Reduce SA","Skip medical questions"]'::jsonb,
 1,'Material non-disclosure on health is a top cause of voided CI claims.',127),
('ultimate-critical-cover','study','compliance','Which marketing claim breaches MAS guidelines?',
 '["UCC covers defined CI conditions per policy wording","Premium varies by age and gender","UCC pays out for any serious illness — guaranteed","Multi-pay subject to policy terms"]'::jsonb,
 2,'Absolute/guarantee claims without basis breach MAS Notice FAA-N03.',128),
('ultimate-critical-cover','study','compliance','Client wants to replace existing CI policy with UCC. Mandatory step?',
 '["No paperwork","Complete Switching/Replacement disclosure form covering loss of in-force benefits, new waiting periods, and exclusions","Cancel old policy first","Hide the switch"]'::jsonb,
 1,'Replacement of life/health policies requires formal disclosure to prevent churning.',129),
('ultimate-critical-cover','study','compliance','For a vulnerable Selected Client (e.g., elderly), what extra step applies?',
 '["Same process","Enhanced explanation, optional trusted-individual involvement, and documented evidence of understanding","Skip suitability","Verbal only"]'::jsonb,
 1,'MAS Selected Client framework requires enhanced safeguards.',130),
('ultimate-critical-cover','study','compliance','You realise you misquoted a CI definition during the sales process. Correct action?',
 '["Stay silent","Proactively correct the client in writing, document the correction, and re-confirm consent before policy issuance","Hope they do not notice","Cancel the case"]'::jsonb,
 1,'Honest correction meets FAA fair-dealing principles.',131),
('ultimate-critical-cover','study','advisory-skills','Client says: "CI is a scam — most claims get rejected." Best response?',
 '["Agree","Share industry claim acceptance statistics and walk through clear definitions / what triggers a payout — turn fear into clarity","Drop CI","Push harder"]'::jsonb,
 1,'Data plus transparent definitions defuses misconceptions.',132),
('ultimate-critical-cover','study','advisory-skills','Client objects: "I will just save the premium myself." Best reframing?',
 '["Agree","Quantify how many years of savings would be needed to match the SA, and the risk of CI striking before savings accumulate — show leverage","Discount premium","Walk away"]'::jsonb,
 1,'CI is leverage: small premium creates immediate large protection.',133),
('ultimate-critical-cover','study','advisory-skills','Best technique to surface the client real CI concern?',
 '["Direct interrogation","Use open and reflective questions: If a serious illness happened tomorrow, what would worry you most about money?","Skip discovery","Push product features"]'::jsonb,
 1,'Emotionally framed open questions surface the real why.',134),
('ultimate-critical-cover','study','advisory-skills','Client compares UCC unfavourably to a competitor CI plan. Strongest move?',
 '["Bash competitor","Side-by-side comparison of definitions, multi-pay structure, premium guarantees and total expected payout — let the client decide","Match the price","Drop the case"]'::jsonb,
 1,'Value-based comparison demonstrates technical mastery.',135),
('ultimate-critical-cover','study','advisory-skills','How should you handle a client who fixates on early-stage CI exclusions?',
 '["Avoid the topic","Walk through exact definitions, give real claim examples, and clarify what is and is not covered — turning ambiguity into confidence","Hide exclusions","Discount premium"]'::jsonb,
 1,'Transparency on exclusions builds trust and reduces dispute risk.',136),
('ultimate-critical-cover','study','advisory-skills','Spouse joins meeting and says "we cannot afford this." Best skill?',
 '["Ignore the spouse","Acknowledge concern, explore household budget collaboratively, and right-size cover to a sustainable level","Push for full cover","End meeting"]'::jsonb,
 1,'Sustainable cover beats over-insurance that lapses.',137),
('ultimate-critical-cover','study','closing','Most ethical CI closing approach?',
 '["Pressure: Sign before health changes","Assumptive close after confirmed suitability and understanding of definitions/exclusions","Hide exclusions","Overpromise"]'::jsonb,
 1,'Ethical closes rest on transparent disclosure and confirmed alignment.',138),
('ultimate-critical-cover','study','closing','Client says "Let me think about it." Best response?',
 '["Walk away","Ask: What specifically would you like to think through? — definitions, premium, or sum assured?","Push immediate signature","Drop case"]'::jsonb,
 1,'Specific clarification surfaces real hesitation without pressure.',139),
('ultimate-critical-cover','study','closing','Best use of a trial close in CI selling?',
 '["At the start","After explaining recommendation, ask alignment questions like Does this size feel right for your family?","Never","Only for HNW"]'::jsonb,
 1,'Trial closes test buy-in and uncover hidden objections.',140),
('ultimate-critical-cover','study','closing','Client agrees in principle but worries about underwriting outcome. Best move?',
 '["Drop the case","Set expectations on possible outcomes (standard / loaded / postponed), submit application, and stay in close communication","Hide the risk","Misrepresent health"]'::jsonb,
 1,'Underwriting transparency reduces post-issue disputes.',141),
('ultimate-critical-cover','study','closing','Post-close, most important advisor action?',
 '["Move to next prospect","Confirm policy issuance, deliver policy with walkthrough, and set an annual review cadence","Stop contact","Aggressively upsell"]'::jsonb,
 1,'Policy delivery and review cadence drive retention and referrals.',142),
('ultimate-critical-cover','study','closing','Ultimate goal of a CI closing conversation?',
 '["Hit target","Earn long-term advisory relationship via suitable, fully-understood recommendation","Max commission","Close fastest"]'::jsonb,
 1,'Sustainable practice prioritises trust and suitability.',143),
-- ============ EXAM BANK (sort_order 36-55) ============
('ultimate-critical-cover','exam','suitability','MOST suitable UCC client?',
 '["Sole breadwinner with mortgage and dependants","Retiree wanting lifetime guaranteed CI","Client with no income or dependants","Client already over-insured"]'::jsonb,
 0,'Term CI maximises cover during peak liability years.',36),
('ultimate-critical-cover','exam','suitability','LEAST suitable for UCC standalone?',
 '["38-year-old professional","Young parent with mortgage","Retiree needing lifetime guaranteed CI cover","Self-employed professional"]'::jsonb,
 2,'Retirees needing lifetime guaranteed CI fit whole-life CI better.',37),
('ultimate-critical-cover','exam','suitability','Best CI sizing approach?',
 '["1x income","Needs-based: income replacement years + liabilities + treatment buffer","Flat $50k","Match spouse only"]'::jsonb,
 1,'Needs-based sizing reflects real recovery and financial impact.',38),
('ultimate-critical-cover','exam','suitability','When is multi-pay CI most relevant?',
 '["Never","Family history of recurrence or extended horizon needing post-first-claim protection","Only retirees","Only HNW"]'::jsonb,
 1,'Multi-pay protects against recurrence and unrelated CI events.',39),
('ultimate-critical-cover','exam','suitability','Client claims "my hospital rider covers CI." Best response?',
 '["Agree","Clarify rider scope — most are reimbursement-only and do not replace lump-sum CI","Cancel rider","Push hospital plan"]'::jsonb,
 1,'Hospital riders typically do not provide income-replacement lump sums.',40),
('ultimate-critical-cover','exam','compliance','Mandatory before UCC recommendation?',
 '["Signature only","Fact-find, basis of recommendation, and disclosures","Verbal note","None"]'::jsonb,
 1,'FAA requires documented suitability and disclosure.',41),
('ultimate-critical-cover','exam','compliance','Client conceals prior screening abnormality. Correct action?',
 '["Submit anyway","Educate on duty of disclosure; obtain proper declaration","Reduce SA","Skip questions"]'::jsonb,
 1,'Statutory duty under the Insurance Act.',42),
('ultimate-critical-cover','exam','compliance','Which marketing claim breaches MAS rules?',
 '["Premium varies by age","Coverage per policy wording","Pays out for any serious illness — guaranteed","Multi-pay subject to terms"]'::jsonb,
 2,'Guarantee/absolute claims breach MAS Notice FAA-N03.',43),
('ultimate-critical-cover','exam','compliance','Replacing existing CI requires?',
 '["Nothing","Switching/Replacement disclosure form","Cancel old plan first","Hide switch"]'::jsonb,
 1,'Mandatory to prevent churning.',44),
('ultimate-critical-cover','exam','compliance','Selected Client (vulnerable) framework requires?',
 '["Same process","Enhanced safeguards and documented understanding","Skip fact-find","Verbal only"]'::jsonb,
 1,'MAS FAA-N16 mandates additional safeguards.',45),
('ultimate-critical-cover','exam','advisory-skills','"CI is a scam, most claims rejected." Best response?',
 '["Agree","Share industry claim stats and walk through definitions","Push harder","Drop CI"]'::jsonb,
 1,'Data and clarity defuse misconceptions ethically.',46),
('ultimate-critical-cover','exam','advisory-skills','"I will just save the premium." Best reframe?',
 '["Agree","Quantify years to self-fund SA and the leverage CI provides","Discount","Walk away"]'::jsonb,
 1,'CI is leverage; self-saving cannot replicate immediate large cover.',47),
('ultimate-critical-cover','exam','advisory-skills','Best skill for surfacing real CI concerns?',
 '["Direct interrogation","Open / reflective emotional questions","Skip discovery","Push features"]'::jsonb,
 1,'Emotional framing surfaces the true why.',48),
('ultimate-critical-cover','exam','advisory-skills','Competitor comparison from client. Best response?',
 '["Bash competitor","Side-by-side definitions, multi-pay, and total expected payout","Match price","Drop case"]'::jsonb,
 1,'Value-based comparison respects client autonomy.',49),
('ultimate-critical-cover','exam','advisory-skills','Spouse says "we cannot afford this." Best skill?',
 '["Ignore","Right-size cover collaboratively to sustainable level","Push full cover","End meeting"]'::jsonb,
 1,'Sustainable cover beats over-insured policies that lapse.',50),
('ultimate-critical-cover','exam','closing','Most ethical CI close?',
 '["Pressure tactics","Assumptive close after confirmed suitability","Hide exclusions","Overpromise"]'::jsonb,
 1,'Ethical closes rest on transparency and alignment.',51),
('ultimate-critical-cover','exam','closing','"Let me think about it." Best response?',
 '["Walk away","Clarify the specific concern and address it now","Push signature","Drop case"]'::jsonb,
 1,'Specific clarification surfaces real hesitation.',52),
('ultimate-critical-cover','exam','closing','Purpose of trial close?',
 '["End meeting","Test alignment and surface objections early","Pressure client","Skip suitability"]'::jsonb,
 1,'Trial closes confirm buy-in before formal close.',53),
('ultimate-critical-cover','exam','closing','Client worried about underwriting outcome. Best move?',
 '["Drop case","Set expectations, submit, and communicate closely","Hide risk","Misrepresent health"]'::jsonb,
 1,'Transparency reduces disputes and builds trust.',54),
('ultimate-critical-cover','exam','closing','Ultimate closing goal?',
 '["Hit target","Long-term advisory relationship via suitable, understood recommendation","Max commission","Close fastest"]'::jsonb,
 1,'Trust and suitability drive sustainable practice.',55);
