INSERT INTO scripts (stage, category, target_audience, script_role, tags, versions, sort_order)
VALUES (
  'Telemarketer — Qualified Leads (Golden Year Partners)',
  'cold-calling',
  'pre-retiree',
  'telemarketer',
  ARRAY['qualified-lead', 'cold-call', 'text-message', 'cpf', 'passive-income', 'retirement'],
  '[{"author": "Template", "content": "Hi, is this (name)?\n\nI''m [name], from Golden Year Partners. This is a courtesy call to inform you that we have received your interest in our retirement planning resources recently.\n\nWe might have called previously but you were busy.\n\nWe specialise in helping Singaporeans create a simple and secure passive income, and we''ve helped many individuals discover ways to maximize their CPF and other assets, ensuring they''re on track to meet their retirement goals.\n\nWould you be opposed in exploring how our expert advisors can help you create a personalized plan?\n\nCan my consultant give you a callback later at around [XX] timing to share more about it?\n\nOkay great, after this call, my manager will send you a text message, and all you have to do, is to reply and acknowledge, is that okay?\n\nAlright great. So just one last thing, this session is just for you to learn more about growing a simple and secure passive income, and as long as you learn something, then that''s good enough!\n\n---\n\n**If asked what''s this about:**\nRetirement planning consultation, we will share more details in the WhatsApp and my consultant will also give you a call later. You can also read https://consult.goldenyearpartners.com/ if needed for more information.\n\n**If asked which company are you from:**\nOur retirement specialists are financial consultants representing AIA specialised in retirement and estate planning 😊 The focus of the assessment call is to see if we are in the right position to value add to you.\nOnly if they believe they can assist you — and if you feel comfortable — will you both explore the option of scheduling a meetup to discuss possible solutions together."}]'::jsonb,
  23
);