// AUTO-GENERATED by scripts/build-day-summaries.mjs. Do not edit by hand.
// Regenerate after changing day markdown files: node scripts/build-day-summaries.mjs
// Source: docs/first-60-days

export type DaySummary = {
  dayNumber: number;
  week: number;
  dayInWeek: number;
  title: string;
  duration: number;
  hasReflection: boolean;
};

export const DAY_SUMMARIES: DaySummary[] = [
  {
    "dayNumber": 1,
    "week": 1,
    "dayInWeek": 1,
    "title": "Welcome — The Journey Begins",
    "duration": 15,
    "hasReflection": false
  },
  {
    "dayNumber": 2,
    "week": 1,
    "dayInWeek": 2,
    "title": "Why Financial Planning Matters",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 3,
    "week": 1,
    "dayInWeek": 3,
    "title": "Four Assurances of This Career",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 4,
    "week": 1,
    "dayInWeek": 4,
    "title": "Growth vs Fixed Mindset",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 5,
    "week": 1,
    "dayInWeek": 5,
    "title": "Purpose-Driven Life — Your Real Why",
    "duration": 30,
    "hasReflection": false
  },
  {
    "dayNumber": 6,
    "week": 1,
    "dayInWeek": 6,
    "title": "Forming Habits That Compound",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 7,
    "week": 2,
    "dayInWeek": 1,
    "title": "The Insurance Industry & AIA Singapore",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 8,
    "week": 2,
    "dayInWeek": 2,
    "title": "Career Sharing — The Path Ahead",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 9,
    "week": 2,
    "dayInWeek": 3,
    "title": "The Poor, The Middle Class, and The Rich",
    "duration": 30,
    "hasReflection": false
  },
  {
    "dayNumber": 10,
    "week": 2,
    "dayInWeek": 4,
    "title": "Your Greatest Purchase = Freedom",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 11,
    "week": 2,
    "dayInWeek": 5,
    "title": "The Cashflow Quadrant — Beyond 9–5",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 12,
    "week": 2,
    "dayInWeek": 6,
    "title": "The Financial Freedom Pyramid",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 13,
    "week": 3,
    "dayInWeek": 1,
    "title": "Job A vs Job B",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 14,
    "week": 3,
    "dayInWeek": 2,
    "title": "The Total Wealth Concept",
    "duration": 35,
    "hasReflection": false
  },
  {
    "dayNumber": 15,
    "week": 3,
    "dayInWeek": 3,
    "title": "Wealth Building — The Principles",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 16,
    "week": 3,
    "dayInWeek": 4,
    "title": "Recurring vs Non-Recurring Revenue",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 17,
    "week": 3,
    "dayInWeek": 5,
    "title": "The Wealth-Builder's Mindset",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 18,
    "week": 3,
    "dayInWeek": 6,
    "title": "The 10X Rule — Mindset Shift",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 19,
    "week": 4,
    "dayInWeek": 1,
    "title": "Prospecting — The Lifeblood of Your Business",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 20,
    "week": 4,
    "dayInWeek": 2,
    "title": "Basic Productivity & Time Efficiency",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 21,
    "week": 4,
    "dayInWeek": 3,
    "title": "Closing & Sales Appointment Framework",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 22,
    "week": 4,
    "dayInWeek": 4,
    "title": "Productivity Principles — Schedule Your Priorities",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 23,
    "week": 4,
    "dayInWeek": 5,
    "title": "Feel-Good Productivity",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 24,
    "week": 4,
    "dayInWeek": 6,
    "title": "The Time Management Matrix — Big Rocks First",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 25,
    "week": 5,
    "dayInWeek": 1,
    "title": "Your Personal Weekly Rhythm",
    "duration": 15,
    "hasReflection": false
  },
  {
    "dayNumber": 26,
    "week": 5,
    "dayInWeek": 2,
    "title": "The 10X Rule in Daily Action",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 27,
    "week": 5,
    "dayInWeek": 3,
    "title": "Your Personal Activity Scorecard — Weekly Ratios & FYC × 4",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 28,
    "week": 5,
    "dayInWeek": 4,
    "title": "Time Value of Money — The Complete Reference",
    "duration": 75,
    "hasReflection": false
  },
  {
    "dayNumber": 29,
    "week": 5,
    "dayInWeek": 5,
    "title": "Compounding — The 8th Wonder of the World",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 30,
    "week": 5,
    "dayInWeek": 6,
    "title": "Dollar Cost Averaging",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 31,
    "week": 6,
    "dayInWeek": 1,
    "title": "TVM Practice Day — Apply Day 28",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 32,
    "week": 6,
    "dayInWeek": 2,
    "title": "The Rule of 72 — Applied",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 33,
    "week": 6,
    "dayInWeek": 3,
    "title": "Understanding CPF — The Singapore Foundation",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 34,
    "week": 6,
    "dayInWeek": 4,
    "title": "What Are Investments?",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 35,
    "week": 6,
    "dayInWeek": 5,
    "title": "Inflation — The Silent Wealth Killer",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 36,
    "week": 6,
    "dayInWeek": 6,
    "title": "TVM Mastery Drill — Live Client Speed Test",
    "duration": 30,
    "hasReflection": false
  },
  {
    "dayNumber": 37,
    "week": 7,
    "dayInWeek": 1,
    "title": "The Approach — Cold, Warm, Follow-Up & Nurture",
    "duration": 35,
    "hasReflection": false
  },
  {
    "dayNumber": 38,
    "week": 7,
    "dayInWeek": 2,
    "title": "Natural Market vs Referred Leads",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 39,
    "week": 7,
    "dayInWeek": 3,
    "title": "Building the Prospect List — Project 100",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 40,
    "week": 7,
    "dayInWeek": 4,
    "title": "Digital Influence — Setting Up Your Presence",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 41,
    "week": 7,
    "dayInWeek": 5,
    "title": "Digital Influence — Content & Engagement",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 42,
    "week": 7,
    "dayInWeek": 6,
    "title": "Digital Influence — Lead-Gen Playbook",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 43,
    "week": 8,
    "dayInWeek": 1,
    "title": "Scripting Your Approach",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 44,
    "week": 8,
    "dayInWeek": 2,
    "title": "Handling Resistance & Objections",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 45,
    "week": 8,
    "dayInWeek": 3,
    "title": "Storytelling — The Hook",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 46,
    "week": 8,
    "dayInWeek": 4,
    "title": "Identifying DISC — Reading People in 60 Seconds",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 47,
    "week": 8,
    "dayInWeek": 5,
    "title": "SPIN — The Framework",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 48,
    "week": 8,
    "dayInWeek": 6,
    "title": "Situation & Problem Questions",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 49,
    "week": 9,
    "dayInWeek": 1,
    "title": "Implication & Need-Payoff Questions",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 50,
    "week": 9,
    "dayInWeek": 2,
    "title": "Client Financial Review — Part 1",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 51,
    "week": 9,
    "dayInWeek": 3,
    "title": "Client Financial Review — Part 2",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 52,
    "week": 9,
    "dayInWeek": 4,
    "title": "Retirement Step-by-Step CST",
    "duration": 35,
    "hasReflection": false
  },
  {
    "dayNumber": 53,
    "week": 9,
    "dayInWeek": 5,
    "title": "CST — The Risks Angle",
    "duration": 20,
    "hasReflection": false
  },
  {
    "dayNumber": 54,
    "week": 9,
    "dayInWeek": 6,
    "title": "Concept Selling",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 55,
    "week": 10,
    "dayInWeek": 1,
    "title": "AIA Solutions — Wealth Products",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 56,
    "week": 10,
    "dayInWeek": 2,
    "title": "AIA Solutions — Protection & Living Benefits",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 57,
    "week": 10,
    "dayInWeek": 3,
    "title": "Investment-Linked Plans — Core Mechanics",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 58,
    "week": 10,
    "dayInWeek": 4,
    "title": "Policy Summary — Riders, Exclusions, Structure",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 59,
    "week": 10,
    "dayInWeek": 5,
    "title": "Proposal Writing + Closing Techniques",
    "duration": 25,
    "hasReflection": false
  },
  {
    "dayNumber": 60,
    "week": 10,
    "dayInWeek": 6,
    "title": "Claims Handling + Graduation",
    "duration": 30,
    "hasReflection": true
  }
];

export const TOTAL_DAYS = DAY_SUMMARIES.length;

export const DAYS_WITH_REFLECTION: ReadonlySet<number> = new Set(
  DAY_SUMMARIES.filter((d) => d.hasReflection).map((d) => d.dayNumber),
);
