// AUTO-GENERATED by scripts/build-day-summaries.mjs. Do not edit by hand.
// Regenerate after changing day markdown files: node scripts/build-day-summaries.mjs
// Source: docs/next-60-days

export type DaySummary = {
  dayNumber: number;
  week: number;
  dayInWeek: number;
  title: string;
  duration: number;
  hasReflection: boolean;
  hasQuiz: boolean;
};

export const DAY_SUMMARIES: DaySummary[] = [
  {
    "dayNumber": 1,
    "week": 1,
    "dayInWeek": 1,
    "title": "Day 1 of your real career: what changes now you're licensed",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 2,
    "week": 1,
    "dayInWeek": 2,
    "title": "The activity math: appointments x close rate x case size",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 3,
    "week": 1,
    "dayInWeek": 3,
    "title": "Your 90-day scorecard: KPIs and revenue math",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 4,
    "week": 1,
    "dayInWeek": 4,
    "title": "Your story: first real draft",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 5,
    "week": 1,
    "dayInWeek": 5,
    "title": "Tonality and salesmanship: how you say it",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 6,
    "week": 1,
    "dayInWeek": 6,
    "title": "Practice: record your 90-second intro",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 7,
    "week": 2,
    "dayInWeek": 1,
    "title": "The intent statement: framework",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 8,
    "week": 2,
    "dayInWeek": 2,
    "title": "The intent statement: your pattern interrupt",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 9,
    "week": 2,
    "dayInWeek": 3,
    "title": "Positioning: the objective advisor",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 10,
    "week": 2,
    "dayInWeek": 4,
    "title": "Personal branding P1: your profile as a compound asset",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 11,
    "week": 2,
    "dayInWeek": 5,
    "title": "Personal branding P2: content and stories rhythm",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 12,
    "week": 2,
    "dayInWeek": 6,
    "title": "Practice: deliver your intent statement to 3 prospects",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 13,
    "week": 3,
    "dayInWeek": 1,
    "title": "The 5 silent questions: what prospects check before they DM you",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 14,
    "week": 3,
    "dayInWeek": 2,
    "title": "Testimonials that actually convert",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 15,
    "week": 3,
    "dayInWeek": 3,
    "title": "Digital pipeline hygiene: where leads actually live",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 16,
    "week": 3,
    "dayInWeek": 4,
    "title": "The DM funnel: reply scripts",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 17,
    "week": 3,
    "dayInWeek": 5,
    "title": "CRAB framework: handling blue ticks",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 18,
    "week": 3,
    "dayInWeek": 6,
    "title": "Practice: 3 posts shipped, 5 DM conversations opened",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 19,
    "week": 4,
    "dayInWeek": 1,
    "title": "Prospecting mindset: the master map",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 20,
    "week": 4,
    "dayInWeek": 2,
    "title": "Reaching out without feeling salesy",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 21,
    "week": 4,
    "dayInWeek": 3,
    "title": "Market Survey: the warm-market framework",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 22,
    "week": 4,
    "dayInWeek": 4,
    "title": "Cold prospecting and the ABCD promises",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 23,
    "week": 4,
    "dayInWeek": 5,
    "title": "Your pipeline board: tools and weekly review",
    "duration": 25,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 24,
    "week": 4,
    "dayInWeek": 6,
    "title": "Practice: 30 outreaches, 5 appointments booked",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 25,
    "week": 5,
    "dayInWeek": 1,
    "title": "Why new FCs under-ask for referrals, and what it costs",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 26,
    "week": 5,
    "dayInWeek": 2,
    "title": "The referral asking framework",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 27,
    "week": 5,
    "dayInWeek": 3,
    "title": "Quality of the ask: context beats script",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 28,
    "week": 5,
    "dayInWeek": 4,
    "title": "The scripts day: FACT Method, 10-Name ask and coaching the client",
    "duration": 25,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 29,
    "week": 5,
    "dayInWeek": 5,
    "title": "The flywheel and the CAR diagnostic",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 30,
    "week": 5,
    "dayInWeek": 6,
    "title": "Practice: 10 referral asks delivered, 3 referrals logged",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 31,
    "week": 6,
    "dayInWeek": 1,
    "title": "DISC: four profiles and the 5-minute speed-read",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 32,
    "week": 6,
    "dayInWeek": 2,
    "title": "D profile: direct, dominant, decisive",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 33,
    "week": 6,
    "dayInWeek": 3,
    "title": "I profile: influencing, social, expressive",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 34,
    "week": 6,
    "dayInWeek": 4,
    "title": "S profile: steady, supportive, patient",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 35,
    "week": 6,
    "dayInWeek": 5,
    "title": "C profile: conscientious, analytical, cautious",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 36,
    "week": 6,
    "dayInWeek": 6,
    "title": "Practice: roleplay all 4 profiles on camera",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 37,
    "week": 7,
    "dayInWeek": 1,
    "title": "Hot buttons I: what actually drives buying",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 38,
    "week": 7,
    "dayInWeek": 2,
    "title": "Hot buttons II: mapping value to emotion",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 39,
    "week": 7,
    "dayInWeek": 3,
    "title": "Hot buttons III: pain-before-gain framing",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 40,
    "week": 7,
    "dayInWeek": 4,
    "title": "Objection turnaround: Anchor-Disrupt-Ask, ART and Iceberg",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 41,
    "week": 7,
    "dayInWeek": 5,
    "title": "Pitch mechanics: confident language and the 4 closes",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 42,
    "week": 7,
    "dayInWeek": 6,
    "title": "Practice: 3 pitches, 3 profiles, 3 hot buttons",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 43,
    "week": 8,
    "dayInWeek": 1,
    "title": "Asking the right questions I: the power question",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 44,
    "week": 8,
    "dayInWeek": 2,
    "title": "Asking the right questions II: silence as a tool",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 45,
    "week": 8,
    "dayInWeek": 3,
    "title": "Sales angles: wealth, risk, legacy, lifestyle",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 46,
    "week": 8,
    "dayInWeek": 4,
    "title": "Choosing the right angle for this prospect",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 47,
    "week": 8,
    "dayInWeek": 5,
    "title": "Analysing products and writing the pitch",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 48,
    "week": 8,
    "dayInWeek": 6,
    "title": "Practice: 1 live pitch on camera, self-reviewed",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 49,
    "week": 9,
    "dayInWeek": 1,
    "title": "Closing I: the trial close and paper-flip social proof",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 50,
    "week": 9,
    "dayInWeek": 2,
    "title": "Closing II: assumptive, choice, urgency",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 51,
    "week": 9,
    "dayInWeek": 3,
    "title": "Closing III: emotional close vs logical close",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 52,
    "week": 9,
    "dayInWeek": 4,
    "title": "The 3 magic questions on objections",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 53,
    "week": 9,
    "dayInWeek": 5,
    "title": "Top 10 objections and scripts",
    "duration": 25,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 54,
    "week": 9,
    "dayInWeek": 6,
    "title": "Practice: 5 objection drills recorded",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 55,
    "week": 10,
    "dayInWeek": 1,
    "title": "Policy restructuring: when it helps and where the ethical line sits",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 56,
    "week": 10,
    "dayInWeek": 2,
    "title": "After sales: onboarding your first client",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 57,
    "week": 10,
    "dayInWeek": 3,
    "title": "Building moments: the touchpoint calendar",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 58,
    "week": 10,
    "dayInWeek": 4,
    "title": "Case study: how a top producer actually runs a week",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 59,
    "week": 10,
    "dayInWeek": 5,
    "title": "Your first $X FYC: reviewing your numbers",
    "duration": 20,
    "hasReflection": false,
    "hasQuiz": true
  },
  {
    "dayNumber": 60,
    "week": 10,
    "dayInWeek": 6,
    "title": "Graduation: the 12-month plan",
    "duration": 45,
    "hasReflection": false,
    "hasQuiz": true
  }
];

export const TOTAL_DAYS = DAY_SUMMARIES.length;

export const DAYS_WITH_REFLECTION: ReadonlySet<number> = new Set(
  DAY_SUMMARIES.filter((d) => d.hasReflection).map((d) => d.dayNumber),
);

export const DAYS_WITHOUT_QUIZ: ReadonlySet<number> = new Set(
  DAY_SUMMARIES.filter((d) => !d.hasQuiz).map((d) => d.dayNumber),
);
